//! JS module generation: a dependency-free ESM `twMerge`/`twJoin` bundle
//! containing the family-guarded pattern table of a project's design system.
//! The build-time scan decides WHICH grammar ships (only the families the
//! project uses); the runtime resolves every class through the compacted
//! pattern matcher `m()` — no G table, no exact entries, no feature flags.

use crate::config::PluginConfig;
use crate::patterns::{type_code, PatternTable};
use std::collections::BTreeMap;

#[derive(Default)]
pub struct GenerateOptions<'a> {
    pub prefix: Option<&'a str>,
    /// Build-time plugin config (see `crate::config`). The config's synthetic
    /// utilities are already part of the design system (so the pattern table
    /// covers them); here only the `conflictingClassGroups` edges are patched
    /// into the per-family conflict lists.
    pub plugin: Option<&'a PluginConfig>,
    /// Emit the runtime extend API (`extendTailwindMerge`, `validators`,
    /// `mergeConfigs`, ...) and the `makeBundle` overlay machinery.
    pub extend: bool,
}

pub fn generate_js(patterns: &PatternTable, opts: &GenerateOptions) -> String {
    let mut js = String::new();
    js.push_str("// Generated by twm-gen — do not edit. Dependency-free ESM (Node 18+).\n");

    // Overlay machinery (m2/makeBundle) ships only for --extend bundles;
    // build-time plugin configs compile fully into the pattern tables.
    let overlay = opts.extend;

    // MC: shortest input length that can hold a conflicting pair or a
    // duplicate (3 chars + space + 3 chars). The matcher can resolve unseen
    // classes, so a table-derived min would be unsafe — the grammar floor
    // 7 always applies.
    js.push_str("const MC=7;\n");
    if let Some(p) = opts.prefix {
        js.push_str(&format!("const PREFIX={};\n", js_string(p)));
    }
    // Cache bound: configurable at runtime via `setCacheSize` (tailwind-merge
    // `cacheSize` parity). 0 disables both caches (`RC` whole-call + `PC`
    // per-class parse) — every merge recomputes, memory stays flat. Both are
    // Map-based LRU caches: touch-on-get, oldest evicted at the bound, no
    // wholesale clears — the hot working set stays hot on long-lived apps.
    if overlay {
        js.push_str(
            "let CS=8192;export function setCacheSize(n){CS=n>0?n|0:0;PC=new Map()}\n",
        );
    } else {
        js.push_str(
            "let CS=8192;export function setCacheSize(n){CS=n>0?n|0:0;PC=new Map();RC=new Map()}\n",
        );
    }

    // W: family id -> list of family ids it conflicts with (own family
    // first, then generated properties and directed edges), the pattern
    // table's full per-family conflict union — the matcher returns conflict
    // lists from W2 for pattern records, but W backs arbitrary-property
    // classes and the container-named postfix special.
    // Build-time plugin edges patch the per-family lists directly: every
    // config family is compiled — the pattern table covers the merged design
    // system — so no runtime overlay is needed.
    let mut family_conflicts = patterns.family_conflicts();
    if let Some(cfg) = opts.plugin {
        let names = &patterns.family_names;
        for (group, targets) in &cfg.conflicting_class_groups {
            let Some(g) = names.iter().position(|n| n == group) else {
                continue;
            };
            for t in targets {
                if let Some(tid) = names.iter().position(|n| n == t) {
                    if !family_conflicts[g].contains(&(tid as u16)) {
                        family_conflicts[g].push(tid as u16);
                    }
                }
            }
        }
        for list in &mut family_conflicts {
            list.sort_unstable();
        }
    }
    js.push_str("const W=[");
    for (f, conflict_ids) in family_conflicts.iter().enumerate() {
        if f > 0 {
            js.push(',');
        }
        js.push('[');
        for (i, id) in conflict_ids.iter().enumerate() {
            if i > 0 {
                js.push(',');
            }
            js.push_str(&id.to_string());
        }
        js.push(']');
    }
    js.push_str("];\n");

    // FN: family id -> family name (JSON strings).
    js.push_str("const FN=[");
    for (i, name) in patterns.family_names.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        js.push_str(&js_string(name));
    }
    js.push_str("];\n");

    // PR: CSS property -> family id, for arbitrary-property classes
    // (`[padding:1rem]` -> `p`). Prototype-less object: fast `in` check
    // in the matcher.
    js.push_str("const PR=Object.assign(Object.create(null),{");
    for (i, (prop, id)) in patterns.prop_family.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        js.push_str(&js_key(prop));
        js.push(':');
        js.push_str(&id.to_string());
    }
    js.push_str("});\n");

    // W2: deduplicated conflict sets (wid = index).
    js.push_str("const W2=[");
    for (i, set) in patterns.conflict_sets.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        js.push('[');
        for (j, id) in set.iter().enumerate() {
            if j > 0 {
                js.push(',');
            }
            js.push_str(&id.to_string());
        }
        js.push(']');
    }
    js.push_str("];\n");

    // TH: each theme set comma-joined into one JS string.
    js.push_str("const TH=[");
    for (i, set) in patterns.theme_sets.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        js.push_str(&js_string(&set.join(",")));
    }
    js.push_str("];\n");

    // KW: keywords comma-joined (keywords contain no commas).
    js.push_str(&format!(
        "const KW={};\n",
        js_string(&patterns.keywords.join(","))
    ));

    // P: flat array of pattern records: [name, wildcard, family_id,
    // conflict_wid, ngroups, (nitems, spec codes...)...] per alternative.
    // Records are collected first (name + JS elements in emission order)
    // so the leading-segment index B below can be built from the exact
    // flat layout.
    let mut records: Vec<Record> = Vec::new();
    for u in &patterns.utilities {
        let name = if u.wildcard {
            &u.name[..u.name.len() - 1]
        } else {
            &u.name
        };
        for a in &u.alts {
            let mut elems: Vec<String> = Vec::new();
            elems.push(js_string(name));
            elems.push(if u.wildcard { "1" } else { "0" }.to_string());
            elems.push(a.family_id.to_string());
            elems.push(a.conflict_wid.to_string());
            elems.push(a.groups.len().to_string());
            for group in &a.groups {
                elems.push(group.len().to_string());
                for code in group {
                    elems.push(code.to_string());
                }
            }
            records.push(Record {
                name: name.to_string(),
                elems,
            });
        }
    }
    js.push_str("const P=[");
    for (i, r) in records.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        for (j, e) in r.elems.iter().enumerate() {
            if j > 0 {
                js.push(',');
            }
            js.push_str(e);
        }
    }
    js.push_str("];\n");

    // BI: leading-segment index over P. Bucket key = first two chars of
    // the record name (the first char alone when the name is one char);
    // value = every [start,end) span of flat indices holding records of
    // that prefix. Contiguous same-prefix runs merge into one span;
    // same-prefix records can still be non-contiguous in P (exact names
    // sort before wildcards), so a bucket may hold several spans —
    // iterating them in emission order preserves the first-match-wins
    // order of the flat scan. Exactly ONE key per prefix: JS object
    // literals collapse duplicate keys (last wins). (Named BI, not B:
    // the feature-flag consts A/B/C already occupy B.)
    let spans = leading_segment_spans(&records);
    js.push_str("const BI=Object.assign(Object.create(null),{");
    for (i, (key, ss)) in spans.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        js.push_str(&js_key(key));
        js.push_str(":[");
        for (j, (a, b)) in ss.iter().enumerate() {
            if j > 0 {
                js.push(',');
            }
            js.push('[');
            js.push_str(&a.to_string());
            js.push(',');
            js.push_str(&b.to_string());
            js.push(']');
        }
        js.push(']');
    }
    js.push_str("});\n");

    // Postfix-special family ids (only the ones that exist in the guarded
    // table). The matcher handles text-lg/7 (font-size + leading conflict)
    // and @container/[name] (named-container family) whenever the postfix
    // parse flag q[3] is set — always on, so unseen postfix classes resolve
    // correctly without scanning.
    if let Some(ld) = patterns.leading {
        js.push_str(&format!("const LD={ld};\n"));
    }
    if let Some(fs) = patterns.font_size {
        js.push_str(&format!("const FS={fs};\n"));
    }
    if let Some(ct) = patterns.container_type {
        js.push_str(&format!("const CT={ct};\n"));
    }
    if let Some(cn) = patterns.container_named {
        js.push_str(&format!("const CN={cn};\n"));
    }

    js.push_str(&validators_js());
    js.push_str(PATTERN_MATCH_JS);

    // ---- overlay machinery (runtime extend API) ----
    if overlay {
        js.push_str(&overlay_machinery_js(patterns));
    }

    js.push_str(PARSE_JS);
    js.push_str(SORT_MODIFIERS_JS);
    js.push_str(TW_JOIN_JS);

    if overlay {
        js.push_str(&tw_merge_extend_js(patterns, opts.prefix));
    } else {
        js.push_str(&tw_merge_js(patterns, opts.prefix));
    }
    js
}

/// One flat pattern record: `name` + the JS elements emitted for it, in
/// emission order.
struct Record {
    name: String,
    elems: Vec<String>,
}

/// Bucket spans over flat pattern records: key = first two chars of the name
/// (the first char alone when the name is one char), value = every
/// `[start,end)` range of flat indices holding records of that prefix, in
/// emission order. Contiguous same-prefix runs are merged into one span.
/// Index 0 is the first element of the first record (the flat array has no
/// leading sentinel).
fn leading_segment_spans(records: &[Record]) -> BTreeMap<String, Vec<(usize, usize)>> {
    let mut spans: BTreeMap<String, Vec<(usize, usize)>> = BTreeMap::new();
    let mut flat = 0;
    for r in records {
        let key: String = r.name.chars().take(2).collect();
        let end = flat + r.elems.len();
        let ss = spans.entry(key).or_default();
        if ss.last().is_some_and(|(_, e)| *e == flat) {
            ss.last_mut().unwrap().1 = end;
        } else {
            ss.push((flat, end));
        }
        flat = end;
    }
    spans
}

/// JSON-quoted JS string literal.
pub fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Object key: unquoted when it is a valid JS identifier, quoted otherwise.
fn js_key(s: &str) -> String {
    let mut chars = s.chars();
    let valid = match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$' => {
            chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
        }
        _ => false,
    };
    if valid {
        s.to_string()
    } else {
        js_string(s)
    }
}

/// Candidate parser: modifiers, important flag, postfix position and external
/// marker. Mirrors `parse-class-name.ts` (plus prefix stripping). Postfix
/// (`po`) and important (`im`) are always computed — the matcher needs them
/// for every class, unseen postfix classes included. Results are memoized per
/// class string (the same optimization tailwind-merge's `cachedParseClassName`
/// applies; class names repeat heavily in practice) in the LRU `PC` bounded at
/// `CS` entries. Result array: `[important, modifiers, base, postfix_present,
/// external, postfix_part]`.
const PARSE_JS: &str = r#"
let PC=new Map();function p(c){let r=PC.get(c);if(r!==undefined){PC.delete(c);PC.set(c,r);return r}if(typeof PREFIX!=='undefined'){const f=PREFIX+':';if(!c.startsWith(f)){r=[0,[],c,0,1,0];if(CS)PC.set(c,r);return r}c=c.slice(f.length)}const m=[];let bs=0,ps=0,ms=0,pp=-1;for(let i=0;i<c.length;i++){const ch=c[i];if(bs===0&&ps===0){if(ch===':'){m.push(c.slice(ms,i));ms=i+1;continue}if(ch==='/'&&pp<0)pp=i}if(ch==='[')bs++;else if(ch===']')bs--;else if(ch==='(')ps++;else if(ch===')')ps--}let b=ms===0?c:c.slice(ms);let im=0;if(b.endsWith('!')){b=b.slice(0,-1);im=1}else if(b.startsWith('!')){b=b.slice(1);im=1}let po=0;if(pp>ms){po=1;b=b.slice(0,pp-ms)}r=[im,m,b,po,0,po?c.slice(pp):0];if(CS){if(PC.size>=CS)PC.delete(PC.keys().next().value);PC.set(c,r)}return r}
"#;

/// Modifier sorting with order-sensitive anchors (port of `sort-modifiers.ts`).
const SORT_MODIFIERS_JS: &str = r#"
const OS=new Set(['*','**','after','backdrop','before','details-content','file','first-letter','first-line','marker','placeholder','selection']);function sm(x){const r=[];let s=[];for(let i=0;i<x.length;i++){const m=x[i];if(m[0]==='['||OS.has(m)){if(s.length){s.sort();r.push(...s);s=[]}r.push(m)}else s.push(m)}if(s.length){s.sort();r.push(...s)}return r}
"#;

/// `twJoin` (port of `tw-join.ts`, itself derived from clsx). The string
/// check is inlined per element so the common all-strings call never pays a
/// `toValue` call (matches the inline loop in `twMerge`'s wrapper).
const TW_JOIN_JS: &str = r#"
export function twJoin(...x){let s='';for(const a of x)if(a){const v=typeof a==='string'?a:toValue(a);if(v){s&&(s+=' ');s+=v}}return s}
function toValue(m){if(typeof m==='string')return m;let s='';for(let k=0;k<m.length;k++){if(m[k]){const v=toValue(m[k]);if(v){s&&(s+=' ');s+=v}}}return s}
"#;

/// `twMergeJoin` (port of `merge-classlist.ts`): right-to-left, last class wins,
/// conflict key = sorted modifiers + important + family. `seen` is a lazily
/// allocated array of family keys checked with `includes` (linear scan beats
/// a Set for the tiny per-family conflict lists) — the same trick
/// tailwind-merge's benchmarked `mergeClassList` uses. Inputs shorter than
/// `MC` (the grammar floor 7) return trimmed+normalized before any split,
/// parse or match; tokenization is a right-to-left charCode scan that slices
/// tokens without allocating a split array. In prefixed bundles, tokens not
/// carrying the prefix can never be Tailwind classes: they are emitted without
/// parsing (identical to the external-token branch). When no prefix is
/// configured the scan is byte-for-byte the plain loop.
///
/// Every class resolves through the pattern matcher `m()` (the G lookup of
/// earlier versions is gone — the guarded pattern table is the only table).
/// When the base (postfix stripped) does not match but the class carries a
/// postfix, the full class name is tried — `aspect-8/11` only matches as a
/// fraction (`aspect-` + `8/11`), mirroring the build-time table's
/// full-name fallback. Postfix classes always run the two special clauses:
/// `text-lg/7` (font-size family) additionally conflicts with `leading-*`,
/// and `@container/[name]` resolves to the named-container family — emitted
/// only when those families exist in the guarded table.
///
/// `twMerge` is the same merge for the 99.9% shape — a single already-joined
/// string (what `clsx()`-based `cn()` utils pass): no rest args, no toValue,
/// no join loop, straight into the `RC` memo and the `M` merge body. The two
/// share the same `RC` result memo and are byte-identical on single-string
/// inputs.
///
/// Whole-call results are memoized in `RC` (input -> output), the same trick
/// as tailwind-merge's opt-in result cache — but always on, because renders
/// (React etc.) repeat identical class strings constantly. `RC` and the
/// per-class parse memo `PC` are Map-based LRU caches bounded at `CS` entries
/// (default 8192, configurable via the exported `setCacheSize(n)`; `0`
/// disables both): touched on access, oldest evicted at the bound, so the hot
/// working set stays hot on long-lived apps with dynamic class strings.
fn tw_merge_js(p: &PatternTable, prefix: Option<&str>) -> String {
    let mut js = String::from(
        "let RC=new Map(),h;export function twMerge(s){h=RC.get(s);if(h!==undefined){RC.delete(s);RC.set(s,h);return h}return M(s)}export function twMergeJoin(...x){if(x.length===1&&typeof x[0]==='string'&&(h=RC.get(x[0]))!==undefined){RC.delete(x[0]);RC.set(x[0],h);return h}let l='';if(x.length===1&&typeof x[0]==='string')l=x[0];else for(const a of x)if(a){const v=typeof a==='string'?a:toValue(a);if(v){l&&(l+=' ');l+=v}}if((h=RC.get(l))!==undefined){RC.delete(l);RC.set(l,h);return h}return M(l)}function M(l){const t=l.trim();if(t.length<MC){let ws=-1;for(let i=0;i<t.length;i++){if(t.charCodeAt(i)<=32){ws=i;break}}const r=ws<0?t:t.replace(/\\s+/g,' ');if(CS)RC.set(l,r);return r}let seen=null,o='',st=t.length;while(st>0){let en=st;while(en>0&&t.charCodeAt(en-1)<=32)en--;let s=en;while(s>0&&t.charCodeAt(s-1)>32)s--;const c=t.slice(s,en);st=s;",
    );
    if let Some(pfx) = prefix {
        js.push_str(&format!(
            "if(!c.startsWith({})){{o=c+(o?' '+o:'');continue}}",
            js_string(&format!("{pfx}:"))
        ));
    }
    js.push_str(
        "const q=p(c);if(q[4]){o=c+(o?' '+o:'');continue}let r=m(q[2]);if(!r&&q[3])r=m(q[2]+q[5]);if(!r){o=c+(o?' '+o:'');continue}let f=r[0],cf=r[1];if(q[3]){",
    );
    if p.font_size.is_some() && p.leading.is_some() {
        js.push_str("if(FS!==undefined&&LD!==undefined&&f===FS&&cf.indexOf(LD)<0)cf=cf.concat(LD);");
    }
    if p.container_type.is_some() && p.container_named.is_some() {
        js.push_str("if(CT!==undefined&&CN!==undefined&&f===CT&&cn(q[2]+q[5]))f=CN,cf=W[CN];");
    }
    js.push_str(
        "}const v=q[1].length===0?'':q[1].length===1?q[1][0]:sm(q[1]).join(':'),k=v+(q[0]?'!':'')+f;if(seen&&seen.length>=64)seen=new Set(seen);if(seen&&(seen.add?seen.has(k):seen.includes(k)))continue;const pre=v+(q[0]?'!':'');if(!seen)seen=[];if(seen.add)for(let j=0;j<cf.length;j++)seen.add(pre+cf[j]);else for(let j=0;j<cf.length;j++)seen.push(pre+cf[j]);o=c+(o?' '+o:'')}if(CS){if(RC.size>=CS)RC.delete(RC.keys().next().value);RC.set(l,o)}return o}",
    );
    js
}

/// Overlay machinery emission: `NF` (compiled family count), the module
/// overlay constants `XO`/`XKW`/`XC`/`OW` (always empty — build-time plugin
/// configs compile fully into the pattern tables), the `m2` matcher and the
/// runtime extend API. Only emitted for `--extend` bundles.
fn overlay_machinery_js(patterns: &PatternTable) -> String {
    let mut js = String::new();

    // NF: first overlay family id; every compiled family id is below it.
    js.push_str(&format!("const NF={};\n", patterns.family_names.len()));

    // XO: overlay records in the same flat P format (name, wildcard, family
    // id, conflict wid (unused, 0), ngroups, (nitems, spec codes...)...).
    // Runtime extendTailwindMerge appends its records here.
    js.push_str("const XO=[];\n");

    // XKW: overlay keyword strings (keyword codes index this array).
    js.push_str("const XKW=[];\n");

    // XC: per-overlay-family conflict id lists, own family id first.
    js.push_str("const XC=[];\n");

    // OW: sparse compiled family id -> overlay family ids (reverse edges:
    // a kept compiled class also drops the overlay families it edges).
    js.push_str("const OW={};\n");

    js.push_str(OVERLAY_MATCH_JS);
    js.push_str(&extend_api_js());
    js
}

/// Named validator list for the `validators` export, in `TYPES` order
/// (the `.t` tag of entry i is i+1).
const VALIDATOR_NAMES: &[&str] = &[
    "isAny",
    "isNumber",
    "isInteger",
    "isPercentage",
    "isFraction",
    "isTshirtSize",
    "isLength",
    "isShadow",
    "isImage",
    "isUrl",
    "isPosition",
    "isRatio",
    "isWeight",
    "isFamilyName",
    "isAngle",
    "isTime",
    "isCustomIdent",
    "isSpacing",
    "isAnyNonArbitrary",
    "isArbitraryLength",
    "isArbitraryNumber",
    "isArbitraryInteger",
    "isArbitraryPercent",
    "isArbitraryFraction",
    "isArbitrarySize",
    "isArbitraryPosition",
    "isArbitraryShadow",
    "isArbitraryImage",
    "isArbitraryWeight",
    "isArbitraryFamilyName",
    "isArbitraryAngle",
    "isArbitraryTime",
    "isArbitraryRatio",
    "isArbitraryIdent",
    "isArbitraryUrl",
    "isArbitraryString",
    "isArbitraryCustomProperty",
    "isArbitraryFunction",
    "isArbitraryAny",
    "isVariableLength",
    "isVariableNumber",
    "isVariableInteger",
    "isVariablePercent",
    "isVariableFraction",
    "isVariableSize",
    "isVariablePosition",
    "isVariableShadow",
    "isVariableImage",
    "isVariableWeight",
    "isVariableFamilyName",
    "isVariableAngle",
    "isVariableTime",
    "isVariableIdent",
    "isVariableUrl",
    "isVariableString",
    "isVariableCustomProperty",
    "isVariableAny",
];

/// Runtime extend API (`--extend`): `TYPEMAP`, the tagged `validators`
/// object, `mergeConfigs`, the lazily-built compiled family-name map and
/// `extendTailwindMerge`/`createTailwindMerge`.
fn extend_api_js() -> String {
    let mut js = String::new();

    // TYPEMAP: every type name -> its spec code (1-based).
    js.push_str("const TYPEMAP={");
    for (i, t) in crate::patterns::TYPES.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        js.push_str(&js_key(t));
        js.push(':');
        js.push_str(&(i + 1).to_string());
    }
    js.push_str("};\n");

    // validators: named placeholders tagged with `.t` = type code; the
    // machinery reads `.t` for runtime config specs.
    js.push_str("const VN=[");
    for (i, n) in VALIDATOR_NAMES.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        js.push_str(&js_string(n));
    }
    js.push_str(
        "];const validators={};for(let i=0;i<VN.length;i++){const f=(v)=>true;f.t=i+1;validators[VN[i]]=f}export{validators}\n",
    );

    // mergeConfigs: append-merge classGroups (top-level and `extend`-wrapped
    // identical), union conflictingClassGroups; fresh arrays, inputs untouched.
    js.push_str(
        "export function mergeConfigs(a,b){const g={},c={};for(const k in a.classGroups)(g[k]=g[k]||[]).push(...a.classGroups[k]);for(const k in a.conflictingClassGroups)(c[k]=c[k]||[]).push(...a.conflictingClassGroups[k]);for(const k in (a.extend||{}).classGroups)(g[k]=g[k]||[]).push(...(a.extend||{}).classGroups[k]);for(const k in (a.extend||{}).conflictingClassGroups)(c[k]=c[k]||[]).push(...(a.extend||{}).conflictingClassGroups[k]);for(const k in b.classGroups)(g[k]=g[k]||[]).push(...b.classGroups[k]);for(const k in b.conflictingClassGroups)(c[k]=c[k]||[]).push(...b.conflictingClassGroups[k]);for(const k in (b.extend||{}).classGroups)(g[k]=g[k]||[]).push(...(b.extend||{}).classGroups[k]);for(const k in (b.extend||{}).conflictingClassGroups)(c[k]=c[k]||[]).push(...(b.extend||{}).conflictingClassGroups[k]);return{classGroups:g,conflictingClassGroups:c}}\n",
    );

    // Lazily-built compiled family-name map (FN is static; built once on the
    // first extend call, copied per instance).
    js.push_str("let FM=0;function fmm(){if(!FM)FM=new Map(FN.map((n,i)=>[n,i]));return FM}\n");

    // extendTailwindMerge: builds an overlay descriptor for the given config
    // (or transformer over a minimal default) and returns a fresh bound
    // twMerge. The config is first normalized like `mergeConfigs`: top-level
    // and `extend`-wrapped classGroups/conflictingClassGroups both apply
    // (same append semantics), and unknown top-level keys throw
    // (`unsupported config key: <name>` — build-time parity). Class groups
    // always EXTEND the compiled catalog: strings and string arrays become
    // static records, `{prefix: [specs]}` objects wildcard records (specs:
    // `<type>` via TYPEMAP, tagged validator functions via `.t`, any other
    // string incl. "" a keyword; `--theme-*` strings are rejected — runtime
    // theme keys are unsupported). Edge names resolve against the compiled
    // families (< NF) and this instance's own groups (>= NF); unknown names
    // are dead edges.
    js.push_str(
        "export function extendTailwindMerge(c){if(typeof c==='function')c=c({classGroups:{},conflictingClassGroups:{}});for(const k in c)if(k!=='classGroups'&&k!=='conflictingClassGroups'&&k!=='extend')throw new Error('unsupported config key: '+k);c=mergeConfigs(c,{});const xo=XO.slice(),xkw=XKW.slice(),xc=XC.slice(),ow=Object.assign({},OW);const nm=new Map(fmm());const b=xc.length;let j=0;for(const g in c.classGroups){const fid=NF+b+j;if(!nm.has(g))nm.set(g,fid);for(const it of c.classGroups[g]){if(typeof it==='string')xo.push(it,0,fid,0,0);else if(Array.isArray(it)){for(let q=0;q<it.length;q++)xo.push(it[q],0,fid,0,0)}else for(const p in it){xo.push(p?p+'-':'',1,fid,0,1,it[p].length);for(let q=0;q<it[p].length;q++){const s=it[p][q];let code;if(typeof s==='function')code=s.t;else if(typeof s==='string'){if(s[0]==='<'){code=TYPEMAP[s.slice(1,-1)];if(!code)throw new Error('unknown type: '+s)}else if(s.startsWith('--'))throw new Error('runtime theme keys are not supported: '+s);else{xkw.push(s);code=4000+xkw.length-1}}else throw new Error('invalid group spec');xo.push(code)}}}xc.push([fid]);j++}for(const g in c.conflictingClassGroups){const sid=nm.get(g);if(sid===undefined)continue;for(const t of c.conflictingClassGroups[g]){const tid=nm.get(t);if(tid===undefined)continue;if(sid<NF){if(tid>=NF){const a=ow[sid]||(ow[sid]=[]);if(a.indexOf(tid)<0)a.push(tid)}}else{const ci=sid-NF;if(xc[ci].indexOf(tid)<0)xc[ci].push(tid)}}}return makeBundle({xo,xkw,xc,ow})}export const createTailwindMerge=extendTailwindMerge;\n",
    );
    js
}

/// Overlay-mode merge tail: `makeBundle(ov)` binds the overlay descriptor
/// (`{xo,xkw,xc,ow}`) plus a per-instance LRU whole-call result cache and
/// returns the bound `twMerge` function (the extend bundle's `twMerge` is
/// variadic, matching the extend API; `twMergeJoin` aliases it). The merge
/// loop mirrors the plain variant — `m()` first, then `m2` for runtime
/// config families; kept compiled classes accumulate `W` plus their `OW`
/// overlay edges, kept overlay classes accumulate `XC`. Results that
/// involved an overlay match are not cached (overlay ids are
/// instance-specific).
fn tw_merge_extend_js(p: &PatternTable, prefix: Option<&str>) -> String {
    let mut js = String::from(
        "function makeBundle(ov){let RC=new Map(),h;function twMerge(...x){if(x.length===1&&typeof x[0]==='string'&&(h=RC.get(x[0]))!==undefined){RC.delete(x[0]);RC.set(x[0],h);return h}let l='';if(x.length===1&&typeof x[0]==='string')l=x[0];else for(const a of x)if(a){const v=typeof a==='string'?a:toValue(a);if(v){l&&(l+=' ');l+=v}}if((h=RC.get(l))!==undefined){RC.delete(l);RC.set(l,h);return h}return M(l)}const twMergeJoin=twMerge;function M(l){const t=l.trim();if(t.length<MC){let ws=-1;for(let i=0;i<t.length;i++){if(t.charCodeAt(i)<=32){ws=i;break}}const r=ws<0?t:t.replace(/\\s+/g,' ');if(CS)RC.set(l,r);return r}let seen=null,o='',oc=0,st=t.length;while(st>0){let en=st;while(en>0&&t.charCodeAt(en-1)<=32)en--;let s=en;while(s>0&&t.charCodeAt(s-1)>32)s--;const c=t.slice(s,en);st=s;",
    );
    if let Some(pfx) = prefix {
        js.push_str(&format!(
            "if(!c.startsWith({})){{o=c+(o?' '+o:'');continue}}",
            js_string(&format!("{pfx}:"))
        ));
    }
    js.push_str(
        "const q=p(c);if(q[4]){o=c+(o?' '+o:'');continue}let r=m(q[2]);if(!r&&q[3])r=m(q[2]+q[5]);if(!r){const r2=m2(q[2],ov);if(r2<0){o=c+(o?' '+o:'');continue}oc=1;let f=NF+r2,cf=ov.xc[r2];const v=q[1].length===0?'':q[1].length===1?q[1][0]:sm(q[1]).join(':'),k=v+(q[0]?'!':'')+f;if(seen&&seen.length>=64)seen=new Set(seen);if(seen&&(seen.add?seen.has(k):seen.includes(k)))continue;const pre=v+(q[0]?'!':'');if(!seen)seen=[];if(seen.add){for(let j=0;j<cf.length;j++)seen.add(pre+cf[j])}else{for(let j=0;j<cf.length;j++)seen.push(pre+cf[j])}o=c+(o?' '+o:'');continue}let f=r[0],cf=r[1];if(q[3]){",
    );
    if p.font_size.is_some() && p.leading.is_some() {
        js.push_str("if(FS!==undefined&&LD!==undefined&&f===FS&&cf.indexOf(LD)<0)cf=cf.concat(LD);");
    }
    if p.container_type.is_some() && p.container_named.is_some() {
        js.push_str("if(CT!==undefined&&CN!==undefined&&f===CT&&cn(q[2]+q[5]))f=CN,cf=W[CN];");
    }
    js.push_str(
        "}const v=q[1].length===0?'':q[1].length===1?q[1][0]:sm(q[1]).join(':'),k=v+(q[0]?'!':'')+f;if(seen&&seen.length>=64)seen=new Set(seen);if(seen&&(seen.add?seen.has(k):seen.includes(k)))continue;const pre=v+(q[0]?'!':'');if(!seen)seen=[];if(seen.add){for(let j=0;j<cf.length;j++)seen.add(pre+cf[j]);const wf=ov.ow[f];if(wf)for(let j=0;j<wf.length;j++)seen.add(pre+wf[j])}else{for(let j=0;j<cf.length;j++)seen.push(pre+cf[j]);const wf=ov.ow[f];if(wf)for(let j=0;j<wf.length;j++)seen.push(pre+wf[j])}o=c+(o?' '+o:'')}if(CS&&!oc){if(RC.size>=CS)RC.delete(RC.keys().next().value);RC.set(l,o)}return o}return twMerge}",
    );
    js.push_str(
        "const MO={xo:XO,xkw:XKW,xc:XC,ow:OW};const TM=makeBundle(MO);export const twMerge=TM;export const twMergeJoin=TM;\n",
    );
    js
}

/// Overlay matcher `m2(v,o)`: linear scan over the instance's flat overlay
/// records (same layout as `P`), mirroring `m()`'s spec-check semantics —
/// keyword match (incl. the explicit empty keyword, the only way an empty
/// suffix matches), type codes and theme sets. Returns the overlay family
/// index or -1. Arbitrary properties are not special-cased: the compiled
/// `m()` handles them first (via the PR table), and runtime overlay
/// records never carry the `[prop:value]` form.
const OVERLAY_MATCH_JS: &str = r#"function m2(v,o){if(v[0]==='-')v=v.slice(1);const xo=o.xo,xkw=o.xkw;for(let i=0;i<xo.length;){const n=xo[i++],w=xo[i++],f=xo[i++],wid=xo[i++],g=xo[i++];if(!(w?(v.length>n.length&&v.startsWith(n))||(v===n.slice(0,-1)):v===n)){for(let j=0;j<g;j++){const c2=xo[i++];i+=c2}continue}const val=w?(v.length>n.length?v.slice(n.length):''):'';let ok=1;for(let j=0;j<g;j++){const c2=xo[i++];let a=0;for(let k=0;k<c2;k++){const s=xo[i++];a=a||(val===''?s>=4000&&xkw[s-4000]==='':s>=5000?th(s-5000).has(val):s>=4000?xkw[s-4000]===val:s&&VT(s,val))}if(!a){ok=0;break}}if(ok)return f-NF}return -1}"#;

/// (type name, JS case body) for `VT`. The `a-*`/`v-*` bodies use `l`
/// (arbitrary label, '' when absent) and `x` (arbitrary inner value).
const VT_CASES: &[(&str, &str)] = &[
    ("any", "1"),
    ("url", "1"),
    ("weight", "N(v)"),
    ("family-name", "!AV(v)&&!V(v)"),
    ("any-non-arbitrary", "!AV(v)&&!V(v)"),
    ("number", "N(v)"),
    ("integer", "I(v)"),
    ("percentage", "v.endsWith('%')&&N(v.slice(0,-1))"),
    ("fraction", "F(v)"),
    ("tshirt", r"/^(\d+(\.\d+)?)?(xs|sm|md|lg|xl)$/.test(v)"),
    ("length", "L(v)"),
    ("shadow", r"/^(inset_)?-?((\d+)?\.?(\d+)[a-z]+|0)_-?((\d+)?\.?(\d+)[a-z]+|0)/.test(v)"),
    (
        "image",
        r"/^(url|image|image-set|cross-fade|element|(repeating-)?(linear|radial|conic)-gradient)\(.+\)$/.test(v)",
    ),
    (
        "position",
        "v==='center'||v==='top'||v==='bottom'||v==='left'||v==='right'||v==='top-left'||v==='left-top'||v==='top-right'||v==='right-top'||v==='bottom-right'||v==='right-bottom'||v==='bottom-left'||v==='left-bottom'",
    ),
    ("ratio", "F(v)||N(v)"),
    ("angle", "N(v)||v.endsWith('deg')||v.endsWith('grad')||v.endsWith('rad')||v.endsWith('turn')"),
    ("time", "N(v)||v.endsWith('ms')||v.endsWith('s')"),
    ("custom-ident", r"/^[a-zA-Z_\-\\][\w\-\\]*$/.test(v)"),
    ("spacing", "v==='px'||N(v)||AV(v)||V(v)"),
    ("a-length", "l?l==='length':L(x)"),
    ("a-number", "l?l==='number':N(x)"),
    ("a-integer", "l?(l==='number'||l==='integer'):N(x)"),
    ("a-percent", "l?(l==='position'||l==='percentage'):(x.endsWith('%')&&N(x.slice(0,-1)))"),
    ("a-fraction", "l?(l==='number'||l==='ratio'):F(x)"),
    ("a-size", "l!==''&&(l==='length'||l==='size'||l==='bg-size')"),
    ("a-position", "l!==''&&(l==='position'||l==='percentage')"),
    ("a-shadow", r"l?l==='shadow':/^(inset_)?-?((\d+)?\.?(\d+)[a-z]+|0)_-?((\d+)?\.?(\d+)[a-z]+|0)/.test(x)"),
    (
        "a-image",
        r"l?(l==='image'||l==='url'):/^(url|image|image-set|cross-fade|element|(repeating-)?(linear|radial|conic)-gradient)\(.+\)$/.test(x)",
    ),
    ("a-weight", "l?(l==='number'||l==='weight'):1"),
    ("a-family-name", "l==='family-name'"),
    ("a-angle", "l===''||l==='angle'"),
    ("a-time", "l===''||l==='time'"),
    ("a-ratio", "l===''||l==='ratio'"),
    ("a-ident", "l===''||l==='custom-ident'"),
    ("a-url", "l===''||l==='url'"),
    ("a-string", "AV(v)"),
    ("a-custom-property", "AV(v)"),
    ("a-function", "AV(v)"),
    ("a-any", "AV(v)"),
    ("v-length", "l==='length'"),
    ("v-family-name", "l==='family-name'"),
    ("v-position", "l==='position'||l==='percentage'"),
    ("v-size", "l==='length'||l==='size'||l==='bg-size'"),
    ("v-image", "l==='image'||l==='url'"),
    ("v-shadow", "l?l==='shadow':1"),
    ("v-weight", "l?(l==='number'||l==='weight'):1"),
    ("v-angle", "l===''||l==='angle'"),
    ("v-time", "l===''||l==='time'"),
    ("v-ident", "l===''||l==='custom-ident'"),
    ("v-url", "l===''||l==='url'"),
    ("v-percent", "l==='percentage'"),
    ("v-number", "l==='number'||l==='integer'"),
    ("v-fraction", "l==='number'||l==='ratio'"),
    ("v-string", "V(v)"),
    ("v-custom-property", "V(v)"),
    ("v-any", "V(v)"),
];

/// Value validators: exact behavioral port of `values.rs` plus the
/// `SpecItem::matches` type switch (`VT`, case numbers from `type_code`).
fn validators_js() -> String {
    let mut js = String::from(
        r#"const LU=/\d+(%|px|r?em|[sdl]?v([hwib]|min|max)|pt|pc|in|cm|mm|cap|ch|ex|r?lh|cq(w|h|i|b|min|max))|\b(calc|min|max|clamp)\(.+\)|^0$/;const CF=/^(rgba?|hsla?|hwb|(ok)?(lab|lch)|color-mix)\(.+\)$/;function N(v){return /^[+-]?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?$/.test(v)||v==='inf'||v==='+inf'||v==='-inf'||v==='infinity'||v==='+infinity'||v==='-infinity'||v==='NaN'||v==='nan'}function I(v){return /^[+-]?\d+$/.test(v)}function L(v){return LU.test(v)&&!CF.test(v)}function AV(v){return /^\[(?:(\w[\w-]*):)?(.+)\]$/.test(v)}function V(v){return /^\((?:(\w[\w-]*):)?(.+)\)$/.test(v)}function F(v){return /^\d+(\.\d+)?\/\d+(\.\d+)?$/.test(v)}function P1(v){const m=/^\[(?:(\w[\w-]*):)?(.+)\]$/.exec(v);return m?[m[1]||'',m[2]]:0}function P2(v){const m=/^\((?:(\w[\w-]*):)?(.+)\)$/.exec(v);return m?[m[1]||'',m[2]]:0}"#,
    );
    js.push_str("function VT(c,v){switch(c){");
    for (name, body) in VT_CASES {
        let code = type_code(name);
        if name.starts_with("a-") || name.starts_with("v-") {
            let parser = if name.starts_with("v-") { "P2" } else { "P1" };
            js.push_str(&format!(
                "case {code}:{{const p={parser}(v);if(!p)return 0;const l=p[0],x=p[1];return {body}}};"
            ));
        } else {
            js.push_str(&format!("case {code}:return {body};"));
        }
    }
    js.push_str("}return 0}");
    js
}

/// Patterns-mode matcher: lazy theme-set/keyword helpers plus `m(v)`, which
/// resolves an unseen class against the pattern table and returns
/// `[family, conflicts]` or 0. Arbitrary properties resolve via the PR
/// property->family table so they merge with the standard classes they write.
/// The flat `P` scan is indexed by the leading-segment table `BI` (see the
/// generator): only the spans whose prefix equals the first two chars of `v`
/// (the first char for one-char `v`) are scanned.
const PATTERN_MATCH_JS: &str = r#"
const THS=[];function th(i){return THS[i]||(THS[i]=new Set(TH[i].split(',')))}let K;function kws(){if(K===undefined)K=KW.split(',');return K}function cn(v){return v.startsWith('@container')&&((v[10]==='/'&&v[11])||(v[11]==='s'&&v[16]&&v.slice(10).startsWith('-size/'))||(v[11]==='n'&&v[18]&&v.slice(10).startsWith('-normal/')))}function m(v){if(v[0]==='['&&v[v.length-1]===']'){const x=v.slice(1,-1),c=x.indexOf(':');if(c>0){const p=x.slice(0,c);if(p&&PR[p]!==undefined){const f=PR[p];return[f,W[f]]}const k='arbitrary..'+p;return[k,[k]]}}if(v[0]==='-')v=v.slice(1);const rs=BI[v.length>1?v[0]+v[1]:v[0]];if(!rs)return 0;for(let r=0;r<rs.length;r++){for(let i=rs[r][0];i<rs[r][1];){const n=P[i++],w=P[i++],f=P[i++],wid=P[i++],g=P[i++];if(!(w?v.length>n.length&&v.startsWith(n):v===n)){for(let j=0;j<g;j++){const c2=P[i++];i+=c2}continue}const val=w?v.slice(n.length):'';let ok=1;for(let j=0;j<g;j++){const c2=P[i++];let a=0;for(let k=0;k<c2;k++){const s=P[i++];a=a||(s>=5000?th(s-5000).has(val):s>=4000?kws()[s-4000]===val:s&&VT(s,val))}if(!a){ok=0;break}}if(ok)return [f,W2[wid]]}}return 0}
"#;
#[cfg(test)]
mod tests {
    use super::*;
    use crate::conflict::ConflictTable;
    use crate::patterns::PatternTable;
    use crate::theme::Theme;
    use crate::utility::DesignSystem;
    use std::collections::HashSet;

    fn mini_ds(css: &str) -> DesignSystem {
        let prog = crate::css::parse(css);
        DesignSystem::from_css(Theme::from_program(&prog), prog.utilities, &[])
    }

    /// Guarded pattern table of the given classes over a mini design system
    /// (p-*, text-* with font-size + color, block).
    fn guarded(classes: &[&str], extra: &HashSet<String>) -> (PatternTable, DesignSystem) {
        let ds = mini_ds(
            r#"
            @theme { --spacing: 0.25rem; --text-2xl: 1.5rem; }
            @utility p-* { padding: --value(--spacing, <length>); }
            @utility text-* { font-size: --value(--text-*, <tshirt>, <length>, <percentage>); }
            @utility text-* { color: --value(<color>); }
            @utility block { display: block; }
        "#,
        );
        let classes: Vec<String> = classes.iter().map(|s| s.to_string()).collect();
        let t = ConflictTable::from_classes(&ds, &classes, None);
        let mut guard: HashSet<String> = t.family_names.iter().cloned().collect();
        guard.extend(extra.iter().cloned());
        (PatternTable::from_design_system_guarded(&ds, &guard), ds)
    }

    fn generate(classes: &[&str], opts: GenerateOptions) -> String {
        let (pat, _) = guarded(classes, &HashSet::new());
        generate_js(&pat, &opts)
    }

    #[test]
    fn generates_matcher_only_esm() {
        let js = generate(&["p-2", "block"], GenerateOptions::default());
        assert!(js.contains("export function twMerge(s)"));
        assert!(js.contains("export function twMergeJoin"));
        assert!(js.contains("export function twJoin"));
        // No G table: the matcher is the only resolver.
        assert!(!js.contains("const G="), "bundle must not contain a G table");
        assert!(js.contains("const P=["), "bundle must contain pattern records");
        assert!(js.contains("function m(v)"), "bundle must contain the matcher");
        // LRU caches.
        assert!(js.contains("let PC=new Map()"));
        assert!(js.contains("let RC=new Map()"));
        // Grammar floor.
        assert!(js.contains("const MC=7;"));
    }

    #[test]
    fn guarded_bundle_drops_unused_families() {
        let (pat, _) = guarded(&["p-2", "block"], &HashSet::new());
        let js = generate_js(&pat, &GenerateOptions::default());
        // p-* and block records are in; text-* records are dropped (neither
        // font-size nor text-color families are used).
        assert!(js.contains("\"p-\""), "p-* record must ship");
        assert!(js.contains("\"block\""), "block record must ship");
        assert!(!js.contains("\"text-\""), "text-* records must be dropped");
        // The guard is closed under conflict edges: p pulls in its 10 side
        // families (px, py, ...) so dynamically-generated side classes still
        // resolve — 12 families total (display, p, 10 sides).
        assert_eq!(pat.family_names.len(), 12, "families: {:?}", pat.family_names);
        let rows = w_rows(&js);
        assert_eq!(rows.len(), 12);
        // p's row: own family + every side family.
        let p = pat.family_names.iter().position(|n| n == "p").unwrap();
        assert_eq!(rows[p].len(), 11, "p row must carry its edges: {:?}", rows[p]);
        // A side family that never resolves (no px-* record in the mini
        // catalog) still has its own row.
        assert!(rows.iter().all(|r| r.contains(&(r[0]))));
    }

    #[test]
    fn generates_prefix() {
        let js = generate(
            &["tw:block", "tw:inline", "tw:p-2"],
            GenerateOptions {
                prefix: Some("tw"),
                ..Default::default()
            },
        );
        assert!(js.contains("const PREFIX=\"tw\""));
        // Prefix tokenizer skip: non-prefixed tokens are emitted without
        // parsing; the unprefixed bundle must not carry the skip.
        assert!(
            js.contains("if(!c.startsWith(\"tw:\")){o=c+(o?' '+o:'');continue}"),
            "prefixed bundle must skip non-prefixed tokens before parsing"
        );
        let plain = generate(&["block"], GenerateOptions::default());
        assert!(
            !plain.contains("if(!c.startsWith(\"tw:\"))"),
            "unprefixed bundle must not contain the prefix skip"
        );
    }

    #[test]
    fn mc_is_grammar_floor() {
        // The matcher can resolve unseen classes, so the short-input fast
        // path must never fire on a pair that could conflict — the grammar
        // floor 7 always applies, no table-derived MC.
        let js = generate(&["overflow-x-auto", "overflow-x-hidden"], GenerateOptions::default());
        assert!(js.contains("const MC=7;"));
    }

    #[test]
    fn extend_emits_runtime_api() {
        let (pat, _) = guarded(&["p-2", "block"], &HashSet::new());
        let js = generate_js(
            &pat,
            &GenerateOptions {
                extend: true,
                ..Default::default()
            },
        );
        assert!(js.contains("export function extendTailwindMerge("));
        assert!(js.contains("export function mergeConfigs("));
        assert!(js.contains("export const createTailwindMerge="));
        assert!(js.contains("const TYPEMAP={"));
        assert!(js.contains("export{validators}"));
        assert!(js.contains("const validators={}"));
        assert!(js.contains("const XO=[]"));
        assert!(js.contains("const XKW=[]"));
        assert!(js.contains("const XC=[]"));
        assert!(js.contains("const OW={}"));
        assert!(js.contains("function makeBundle("));
        assert!(js.contains("function m2("));
        assert!(js.contains("const MC=7;"), "extend mode floors MC at 7");
        assert!(js.contains("export const twMerge=TM"), "module twMerge = makeBundle(MO)");
        // The emitted runtime machinery must be brace/paren balanced (the
        // overlay lines carry no brace/paren characters inside data strings).
        for line in js.lines() {
            if ["const TYPEMAP", "const VN", "mergeConfigs", "fmm()", "extendTailwindMerge", "makeBundle", "m2(v,o)"]
                .iter()
                .any(|needle| line.contains(needle))
            {
                let opens = line.matches('{').count() + line.matches('(').count();
                let closes = line.matches('}').count() + line.matches(')').count();
                assert_eq!(
                    opens, closes,
                    "unbalanced machinery line: {}",
                    &line[..line.len().min(160)]
                );
            }
        }
    }

    /// Extract the emitted `W` table rows ([family id] -> conflict ids).
    fn w_rows(js: &str) -> Vec<Vec<u16>> {
        let start = js.find("const W=[").expect("W emitted") + "const W=[".len();
        let end = js[start..].find("];").expect("W terminates") + start;
        js[start..end]
            .split("],[")
            .map(|part| {
                part.trim_start_matches('[')
                    .trim_end_matches(']')
                    .split(',')
                    .filter_map(|s| s.parse().ok())
                    .collect()
            })
            .collect()
    }

    #[test]
    fn plugin_edges_patch_family_conflict_rows() {
        // The --config families compile into the pattern table (the design
        // system already includes the synthetic utilities), so the edges
        // patch the per-family W rows directly instead of emitting overlay
        // machinery.
        let ds = {
            let prog = crate::css::parse(
                r#"
                @theme { --spacing: 0.25rem; }
                @utility p-* { padding: --value(--spacing, <length>); }
                @utility block { display: block; }
            "#,
            );
            let cfg = crate::config::parse_config_json(
                r#"{
                    "classGroups": {
                        "rtl.ps": [{ "ps": ["<length>"] }],
                        "rtl.pe": [{ "pe": ["<length>"] }]
                    },
                    "conflictingClassGroups": { "p": ["rtl.ps", "rtl.pe"] }
                }"#,
            )
            .unwrap();
            DesignSystem::from_css(
                Theme::from_program(&prog),
                prog.utilities,
                &cfg.to_synthetic_utilities(),
            )
        };
        let classes: Vec<String> = vec!["p-2".to_string(), "block".to_string()];
        let t = ConflictTable::from_classes(&ds, &classes, None);
        let mut guard: HashSet<String> = t.family_names.iter().cloned().collect();
        guard.insert("rtl.ps".to_string());
        guard.insert("rtl.pe".to_string());
        guard.insert("p".to_string());
        let pat = PatternTable::from_design_system_guarded(&ds, &guard);
        let cfg = crate::config::parse_config_json(
            r#"{
                "classGroups": {
                    "rtl.ps": [{ "ps": ["<length>"] }],
                    "rtl.pe": [{ "pe": ["<length>"] }]
                },
                "conflictingClassGroups": { "p": ["rtl.ps", "rtl.pe"] }
            }"#,
        )
        .unwrap();
        let js = generate_js(
            &pat,
            &GenerateOptions {
                plugin: Some(&cfg),
                ..Default::default()
            },
        );
        let rows = w_rows(&js);
        let p = pat.family_names.iter().position(|n| n == "p").unwrap();
        let ps = pat.family_names.iter().position(|n| n == "rtl.ps").unwrap();
        let pe = pat.family_names.iter().position(|n| n == "rtl.pe").unwrap();
        assert!(
            rows[p].contains(&(ps as u16)) && rows[p].contains(&(pe as u16)),
            "W row for p must include the edge targets rtl.ps/rtl.pe: {:?}",
            rows[p]
        );
        assert!(
            !rows[ps].contains(&(p as u16)),
            "W row for rtl.ps must NOT include p — the edge is one-directional: {:?}",
            rows[ps]
        );
        // Every config family compiles into the pattern table, so the overlay
        // machinery is absent from plain bundles entirely.
        assert!(
            !js.contains("function m2(") && !js.contains("makeBundle"),
            "plain bundle must not carry overlay machinery"
        );
    }

    #[test]
    fn b_spans_cover_every_record_exactly_once() {
        // Synthetic records with non-contiguous same-prefix runs and a
        // one-char name (which must key on its single char).
        let records = vec![
            Record {
                name: "ab".into(),
                elems: vec![String::new(); 3],
            },
            Record {
                name: "ab".into(),
                elems: vec![String::new(); 2],
            },
            Record {
                name: "ac".into(),
                elems: vec![String::new(); 4],
            },
            Record {
                name: "ab".into(),
                elems: vec![String::new(); 5],
            },
            Record {
                name: "a".into(),
                elems: vec![String::new(); 2],
            },
            Record {
                name: "ab".into(),
                elems: vec![String::new(); 1],
            },
        ];
        let spans = leading_segment_spans(&records);
        assert_eq!(spans["ab"], vec![(0, 5), (9, 14), (16, 17)]);
        assert_eq!(spans["ac"], vec![(5, 9)]);
        assert_eq!(spans["a"], vec![(14, 16)]);
        // No overlap: every flat index is inside at most one span.
        let mut ranges: Vec<(usize, usize)> = spans.values().flatten().copied().collect();
        ranges.sort_unstable();
        for w in ranges.windows(2) {
            assert!(
                w[0].1 <= w[1].0,
                "spans overlap or cross: {:?}",
                (w[0], w[1])
            );
        }
        // Every record covered by exactly one span of its own prefix, at its
        // exact flat position (index 0 = first record's first element).
        let mut covered: BTreeMap<(usize, usize), usize> = BTreeMap::new();
        let mut flat = 0;
        for r in &records {
            let key: String = r.name.chars().take(2).collect();
            let end = flat + r.elems.len();
            let ss = spans.get(&key).expect("bucket key present");
            let hits = ss
                .iter()
                .filter(|(a, b)| *a <= flat && end <= *b)
                .count();
            assert_eq!(
                hits, 1,
                "record {:?} at flat {}..{} must be inside exactly one span of its own prefix",
                r.name, flat, end
            );
            *covered.entry((flat, end)).or_insert(0) += 1;
            flat = end;
        }
        assert!(
            covered.values().all(|&c| c == 1),
            "each record range must be covered exactly once"
        );
    }

    #[test]
    fn b_emission_has_no_duplicate_keys() {
        let (pat, _) = guarded(&["p-2", "block"], &HashSet::new());
        let js = generate_js(&pat, &GenerateOptions::default());
        // B: exactly one emitted key per prefix (duplicate object-literal
        // keys would collapse with only the LAST span surviving).
        let b_start = js.find("const BI=").expect("BI emitted");
        let b_end = js[b_start..].find("});\n").expect("BI terminates") + b_start;
        let body = &js[b_start + "const BI=Object.assign(Object.create(null),{".len()..b_end];
        let keys: Vec<&str> = body
            .split(',')
            .filter(|s| s.ends_with(":["))
            .map(|s| s.split(':').next().unwrap())
            .collect();
        let mut sorted = keys.clone();
        sorted.sort();
        sorted.dedup();
        assert_eq!(
            sorted.len(),
            keys.len(),
            "duplicate B keys in emission: {:?}",
            keys
        );
    }
}
