//! JS module generation: a dependency-free ESM `twMerge`/`twJoin` bundle
//! containing only the classes a project uses, with feature-flagged runtime
//! helpers. No Tailwind parser at runtime — O(1) table lookups. With
//! `GenerateOptions::patterns`, the bundle additionally embeds the full
//! design-system pattern table so unseen classes still resolve.

use crate::config::{GroupItem, GroupSpec, PluginConfig};
use crate::conflict::ConflictTable;
use crate::patterns::{type_code, KW_OFFSET, PatternTable, TH_OFFSET};
use crate::utility::DesignSystem;
use std::collections::{BTreeMap, HashMap};

#[derive(Default)]
pub struct GenerateOptions<'a> {
    pub prefix: Option<&'a str>,
    /// Emit the pattern table + pattern merge loop (requires passing the
    /// pattern table to `generate_js`).
    pub patterns: bool,
    /// Build-time plugin config (see `crate::config`). Exact mode:
    /// wildcard-bearing groups additionally emit overlay records + overlay
    /// conflict tables (the design system must already include the synthetic
    /// utilities). Patterns mode: config families are fully compiled and
    /// only the conflict lists are patched.
    pub plugin: Option<&'a PluginConfig>,
    /// Emit the runtime extend API (`extendTailwindMerge`, `validators`,
    /// `mergeConfigs`, ...) and the `makeBundle` overlay machinery. With no
    /// plugin and no extend the emitted JS is byte-identical to the plain
    /// output.
    pub extend: bool,
    /// Design system — needed for the theme sets of exact-mode overlay
    /// wildcard records. Unused in patterns mode.
    pub ds: Option<&'a DesignSystem>,
}

pub fn generate_js(
    table: &ConflictTable,
    patterns: Option<&PatternTable>,
    opts: &GenerateOptions,
) -> String {
    let mut js = String::new();
    js.push_str("// Generated by twm-gen — do not edit. Dependency-free ESM (Node 18+).\n");

    let pat_mode = opts.patterns && patterns.is_some();
    // Overlay machinery (m2/makeBundle) is present for build-time plugin
    // configs and for --extend bundles.
    let overlay = opts.plugin.is_some() || opts.extend;
    let needs_postfix = table.needs_postfix;
    let needs_important = table.needs_important;
    let needs_fallback = !table.arb_fallbacks.is_empty();

    if pat_mode {
        js.push_str(&format!(
            "const A={needs_postfix},B={needs_important},C={needs_fallback},D=1;\n"
        ));
    } else {
        js.push_str(&format!(
            "const A={needs_postfix},B={needs_important},C={needs_fallback};\n"
        ));
    }
    if let Some(p) = opts.prefix {
        js.push_str(&format!("const PREFIX={};\n", js_string(p)));
    }
    // MC: shortest input length that can contain a conflict, derived at build
    // time from the table (exact mode) or kept at the default-grammar floor
    // 7 (patterns mode: the matcher can resolve unseen classes, so a
    // table-derived min would be unsafe there — same for any bundle with
    // overlay machinery, whose runtime classes are unknown at build time).
    let mc = if pat_mode || overlay {
        7
    } else {
        match table.min_conflict_pair_len() {
            Some(n) => n,
            // No conflicting pair: every input short-circuits to normalize.
            None => usize::MAX,
        }
    };
    if mc == usize::MAX {
        js.push_str("const MC=Number.MAX_SAFE_INTEGER;\n");
    } else {
        js.push_str(&format!("const MC={mc};\n"));
    }
    // Cache bound: configurable at runtime via `setCacheSize` (tailwind-merge
    // `cacheSize` parity). 0 disables both caches (`RC` whole-call + `PC`
    // per-class parse) — every merge recomputes, memory stays flat. In
    // overlay bundles `RC` lives inside `makeBundle` (per-instance), so
    // setCacheSize only resets the shared `PC`; instance caches respect the
    // bound at access.
    if overlay {
        js.push_str(
            "let CS=8192;export function setCacheSize(n){CS=n>0?n|0:0;PC=Object.create(null);PCn=0}\n",
        );
    } else {
        js.push_str(
            "let CS=8192;export function setCacheSize(n){CS=n>0?n|0:0;RC=Object.create(null);RCn=0;PC=Object.create(null);PCn=0}\n",
        );
    }

    // GROUPS: base class name -> family id. Postfix variants get a trailing
    // '/' key; arbitrary-value fallbacks get a 'prefix-arb' key.
    // Object.create(null) gives a prototype-less table so the hot path can use
    // the fast `key in G` operator (no inherited-key false positives, and `in`
    // is far cheaper than Object.prototype.hasOwnProperty.call).
    js.push_str("const G=Object.assign(Object.create(null),{");
    let mut first = true;
    let emit = |js: &mut String, first: &mut bool, key: &str, id: u16| {
        if !*first {
            js.push(',');
        }
        *first = false;
        js.push_str(&js_key(key));
        js.push(':');
        js.push_str(&id.to_string());
    };
    let mut entries: Vec<(&String, &crate::conflict::ClassKey)> = table.entries.iter().collect();
    entries.sort_by(|a, b| a.0.cmp(b.0));
    for (base, key) in entries {
        emit(&mut js, &mut first, base, table.family_id_of(&key.family));
    }
    let mut postfix: Vec<(&String, &crate::conflict::ClassKey)> =
        table.postfix_entries.iter().collect();
    postfix.sort_by(|a, b| a.0.cmp(b.0));
    for (base, key) in postfix {
        emit(&mut js, &mut first, base, table.family_id_of(&key.family));
    }
    let mut fallbacks: Vec<(&String, &crate::conflict::ClassKey)> =
        table.arb_fallbacks.iter().collect();
    fallbacks.sort_by(|a, b| a.0.cmp(b.0));
    for (prefix, key) in fallbacks {
        emit(
            &mut js,
            &mut first,
            &format!("{prefix}arb"),
            table.family_id_of(&key.family),
        );
    }
    js.push_str("});\n");

    // W: family id -> list of family ids it conflicts with (own family
    // first, then generated properties and directed edges). In patterns mode
    // the pattern table's full per-family conflict union is used instead.
    // Build-time plugin edges (patterns mode) patch the per-family lists
    // directly: every config family is compiled — the pattern table covers
    // the merged design system — so no overlay is needed. (`family_conflicts`
    // returns fresh owned lists; the shared `conflict_sets` stay untouched.)
    let family_conflicts: Vec<Vec<u16>> = if pat_mode {
        let mut fc = patterns.unwrap().family_conflicts();
        if let Some(cfg) = opts.plugin {
            let names = &patterns.unwrap().family_names;
            for (group, targets) in &cfg.conflicting_class_groups {
                let Some(g) = names.iter().position(|n| n == group) else {
                    continue;
                };
                for t in targets {
                    if let Some(tid) = names.iter().position(|n| n == t) {
                        if !fc[g].contains(&(tid as u16)) {
                            fc[g].push(tid as u16);
                        }
                    }
                }
            }
            for list in &mut fc {
                list.sort_unstable();
            }
        }
        fc
    } else {
        table.family_conflicts()
    };
    js.push_str("const W=[");
    for (f, conflict_ids) in family_conflicts.iter().enumerate() {
        if f > 0 {
            js.push(',');
        }
        js.push('[');
        for (i, id) in conflict_ids.iter().enumerate() {
            if i > 0 {
                js.push(',');
            }
            js.push_str(&id.to_string());
        }
        js.push(']');
    }
    js.push_str("];\n");

    if pat_mode {
        let p = patterns.unwrap();

        // FN: family id -> family name (JSON strings).
        js.push_str("const FN=[");
        for (i, name) in p.family_names.iter().enumerate() {
            if i > 0 {
                js.push(',');
            }
            js.push_str(&js_string(name));
        }
        js.push_str("];\n");

        // PR: CSS property -> family id, for arbitrary-property classes
        // (`[padding:1rem]` -> `p`). Prototype-less object: fast `in` check
        // in the matcher.
        js.push_str("const PR=Object.assign(Object.create(null),{");
        for (i, (prop, id)) in p.prop_family.iter().enumerate() {
            if i > 0 {
                js.push(',');
            }
            js.push_str(&js_key(prop));
            js.push(':');
            js.push_str(&id.to_string());
        }
        js.push_str("});\n");

        // W2: deduplicated conflict sets (wid = index).
        js.push_str("const W2=[");
        for (i, set) in p.conflict_sets.iter().enumerate() {
            if i > 0 {
                js.push(',');
            }
            js.push('[');
            for (j, id) in set.iter().enumerate() {
                if j > 0 {
                    js.push(',');
                }
                js.push_str(&id.to_string());
            }
            js.push(']');
        }
        js.push_str("];\n");

        // TH: each theme set comma-joined into one JS string.
        js.push_str("const TH=[");
        for (i, set) in p.theme_sets.iter().enumerate() {
            if i > 0 {
                js.push(',');
            }
            js.push_str(&js_string(&set.join(",")));
        }
        js.push_str("];\n");

        // KW: keywords comma-joined (keywords contain no commas).
        js.push_str(&format!("const KW={};\n", js_string(&p.keywords.join(","))));

        // P: flat array of pattern records: [name, wildcard, family_id,
        // conflict_wid, ngroups, (nitems, spec codes...)...] per alternative.
        // Records are collected first (name + JS elements in emission order)
        // so the leading-segment index B below can be built from the exact
        // flat layout.
        let mut records: Vec<Record> = Vec::new();
        for u in &p.utilities {
            let name = if u.wildcard {
                &u.name[..u.name.len() - 1]
            } else {
                &u.name
            };
            for a in &u.alts {
                let mut elems: Vec<String> = Vec::new();
                elems.push(js_string(name));
                elems.push(if u.wildcard { "1" } else { "0" }.to_string());
                elems.push(a.family_id.to_string());
                elems.push(a.conflict_wid.to_string());
                elems.push(a.groups.len().to_string());
                for group in &a.groups {
                    elems.push(group.len().to_string());
                    for code in group {
                        elems.push(code.to_string());
                    }
                }
                records.push(Record {
                    name: name.to_string(),
                    elems,
                });
            }
        }
        js.push_str("const P=[");
        for (i, r) in records.iter().enumerate() {
            if i > 0 {
                js.push(',');
            }
            for (j, e) in r.elems.iter().enumerate() {
                if j > 0 {
                    js.push(',');
                }
                js.push_str(e);
            }
        }
        js.push_str("];\n");

        // BI: leading-segment index over P. Bucket key = first two chars of
        // the record name (the first char alone when the name is one char);
        // value = every [start,end) span of flat indices holding records of
        // that prefix. Contiguous same-prefix runs merge into one span;
        // same-prefix records can still be non-contiguous in P (exact names
        // sort before wildcards), so a bucket may hold several spans —
        // iterating them in emission order preserves the first-match-wins
        // order of the flat scan. Exactly ONE key per prefix: JS object
        // literals collapse duplicate keys (last wins). (Named BI, not B:
        // the feature-flag consts A/B/C already occupy B.)
        let spans = leading_segment_spans(&records);
        js.push_str("const BI=Object.assign(Object.create(null),{");
        for (i, (key, ss)) in spans.iter().enumerate() {
            if i > 0 {
                js.push(',');
            }
            js.push_str(&js_key(key));
            js.push_str(":[");
            for (j, (a, b)) in ss.iter().enumerate() {
                if j > 0 {
                    js.push(',');
                }
                js.push('[');
                js.push_str(&a.to_string());
                js.push(',');
                js.push_str(&b.to_string());
                js.push(']');
            }
            js.push(']');
        }
        js.push_str("});\n");

        // Postfix-special family ids (only the ones that exist).
        if let Some(ld) = p.leading {
            js.push_str(&format!("const LD={ld};\n"));
        }
        if let Some(fs) = p.font_size {
            js.push_str(&format!("const FS={fs};\n"));
        }
        if let Some(ct) = p.container_type {
            js.push_str(&format!("const CT={ct};\n"));
        }
        if let Some(cn) = p.container_named {
            js.push_str(&format!("const CN={cn};\n"));
        }

        js.push_str(&validators_js());
        js.push_str(PATTERN_MATCH_JS);
    } else if opts.extend {
        // FN: family id -> name. Patterns mode always emits it; the runtime
        // extend API needs it, so exact-extend bundles emit it too.
        js.push_str("const FN=[");
        for (i, name) in table.family_names.iter().enumerate() {
            if i > 0 {
                js.push(',');
            }
            js.push_str(&js_string(name));
        }
        js.push_str("];\n");
    }

    // ---- overlay machinery (build-time plugin overlay + runtime extend) ----
    if overlay {
        js.push_str(&overlay_machinery_js(table, patterns, pat_mode, opts));
    }

    if pat_mode {
        js.push_str(PARSE_PATTERNS_JS);
    } else {
        js.push_str(PARSE_JS);
    }
    js.push_str(SORT_MODIFIERS_JS);
    js.push_str(TW_JOIN_JS);

    if overlay {
        js.push_str(&tw_merge_extend_js(pat_mode, patterns, opts.prefix));
    } else if pat_mode {
        js.push_str(&tw_merge_patterns_js(patterns.unwrap(), opts.prefix));
    } else {
        js.push_str(&tw_merge_js(opts.prefix));
    }
    js
}

/// One flat pattern record: `name` + the JS elements emitted for it, in
/// emission order.
struct Record {
    name: String,
    elems: Vec<String>,
}

/// Bucket spans over flat pattern records: key = first two chars of the name
/// (the first char alone when the name is one char), value = every
/// `[start,end)` range of flat indices holding records of that prefix, in
/// emission order. Contiguous same-prefix runs are merged into one span.
/// Index 0 is the first element of the first record (the flat array has no
/// leading sentinel).
fn leading_segment_spans(records: &[Record]) -> BTreeMap<String, Vec<(usize, usize)>> {
    let mut spans: BTreeMap<String, Vec<(usize, usize)>> = BTreeMap::new();
    let mut flat = 0;
    for r in records {
        let key: String = r.name.chars().take(2).collect();
        let end = flat + r.elems.len();
        let ss = spans.entry(key).or_default();
        if ss.last().is_some_and(|(_, e)| *e == flat) {
            ss.last_mut().unwrap().1 = end;
        } else {
            ss.push((flat, end));
        }
        flat = end;
    }
    spans
}

/// JSON-quoted JS string literal.
pub fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Object key: unquoted when it is a valid JS identifier, quoted otherwise.
fn js_key(s: &str) -> String {
    let mut chars = s.chars();
    let valid = match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$' => {
            chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
        }
        _ => false,
    };
    if valid {
        s.to_string()
    } else {
        js_string(s)
    }
}

/// Candidate parser: modifiers, important flag, postfix position and
/// arbitrary fallback prefix. Mirrors `parse-class-name.ts` (plus prefix
/// stripping and the feature flags A=postfix, B=important, C=fallback).
/// Results are memoized per class string (same optimization tailwind-merge's
/// `cachedParseClassName` applies; class names repeat heavily in practice),
/// with the memo bounded at 8192 entries to cap memory on long-lived apps.
const PARSE_JS: &str = r#"
let PC=Object.create(null),PCn=0;function p(c){let r=PC[c];if(r!==undefined)return r;if(CS&&PCn>CS){PC=Object.create(null);PCn=0}if(typeof PREFIX!=='undefined'){const f=PREFIX+':';if(!c.startsWith(f)){r=[0,[],c,0,0,1];if(CS){PC[c]=r;PCn++}return r}c=c.slice(f.length)}const m=[];let bs=0,ps=0,ms=0,pp=-1;for(let i=0;i<c.length;i++){const ch=c[i];if(bs===0&&ps===0){if(ch===':'){m.push(c.slice(ms,i));ms=i+1;continue}if(ch==='/'&&pp<0)pp=i}if(ch==='[')bs++;else if(ch===']')bs--;else if(ch==='(')ps++;else if(ch===')')ps--}let b=ms===0?c:c.slice(ms);let im=0;if(B){if(b.endsWith('!')){b=b.slice(0,-1);im=1}else if(b.startsWith('!')){b=b.slice(1);im=1}}let po=0;if(A&&pp>ms){po=1;b=b.slice(0,pp-ms)}let ar=0;if(C){const a0=b.indexOf('['),a1=b.indexOf('(');const ai=a0<0?a1:a1<0?a0:a0<a1?a0:a1;if(ai>0)ar=b.slice(0,ai)}r=[im,m,b,po,ar,0];if(CS){PC[c]=r;PCn++}return r}
"#;

/// Patterns-mode variant of `PARSE_JS`: identical, but the result array is
/// `[im,m,b,po,ar,ext,pf]` where `pf` is the postfix part (`/...`) when one
/// was found, else 0.
const PARSE_PATTERNS_JS: &str = r#"
let PC=Object.create(null),PCn=0;function p(c){let r=PC[c];if(r!==undefined)return r;if(CS&&PCn>CS){PC=Object.create(null);PCn=0}if(typeof PREFIX!=='undefined'){const f=PREFIX+':';if(!c.startsWith(f)){r=[0,[],c,0,0,1,0];if(CS){PC[c]=r;PCn++}return r}c=c.slice(f.length)}const m=[];let bs=0,ps=0,ms=0,pp=-1;for(let i=0;i<c.length;i++){const ch=c[i];if(bs===0&&ps===0){if(ch===':'){m.push(c.slice(ms,i));ms=i+1;continue}if(ch==='/'&&pp<0)pp=i}if(ch==='[')bs++;else if(ch===']')bs--;else if(ch==='(')ps++;else if(ch===')')ps--}let b=ms===0?c:c.slice(ms);let im=0;if(B){if(b.endsWith('!')){b=b.slice(0,-1);im=1}else if(b.startsWith('!')){b=b.slice(1);im=1}}let po=0;if(A&&pp>ms){po=1;b=b.slice(0,pp-ms)}let ar=0;if(C){const a0=b.indexOf('['),a1=b.indexOf('(');const ai=a0<0?a1:a1<0?a0:a0<a1?a0:a1;if(ai>0)ar=b.slice(0,ai)}r=[im,m,b,po,ar,0,po?c.slice(pp):0];if(CS){PC[c]=r;PCn++}return r}
"#;

/// Modifier sorting with order-sensitive anchors (port of `sort-modifiers.ts`).
const SORT_MODIFIERS_JS: &str = r#"
const OS=new Set(['*','**','after','backdrop','before','details-content','file','first-letter','first-line','marker','placeholder','selection']);function sm(x){const r=[];let s=[];for(let i=0;i<x.length;i++){const m=x[i];if(m[0]==='['||OS.has(m)){if(s.length){s.sort();r.push(...s);s=[]}r.push(m)}else s.push(m)}if(s.length){s.sort();r.push(...s)}return r}
"#;

/// `twJoin` (port of `tw-join.ts`, itself derived from clsx). The string
/// check is inlined per element so the common all-strings call never pays a
/// `toValue` call (matches the inline loop in `twMerge`'s wrapper).
const TW_JOIN_JS: &str = r#"
export function twJoin(...x){let s='';for(const a of x)if(a){const v=typeof a==='string'?a:toValue(a);if(v){s&&(s+=' ');s+=v}}return s}
function toValue(m){if(typeof m==='string')return m;let s='';for(let k=0;k<m.length;k++){if(m[k]){const v=toValue(m[k]);if(v){s&&(s+=' ');s+=v}}}return s}
"#;

/// `twMergeJoin` (port of `merge-classlist.ts`): right-to-left, last class wins,
/// conflict key = sorted modifiers + important + family. `seen` is a lazily
/// allocated array of family keys checked with `includes` (linear scan beats
/// a Set for the tiny per-family conflict lists) — the same trick
/// tailwind-merge's benchmarked `mergeClassList` uses. Inputs shorter than
/// the build-time `MC` constant (the project's shortest conflicting pair)
/// return trimmed+normalized before any split/parse; tokenization is a
/// right-to-left charCode scan that slices tokens without allocating a split
/// array. In prefixed bundles, tokens not carrying the prefix can never be
/// Tailwind classes: they are emitted without parsing (identical to the
/// external-token branch). When no prefix is configured the scan is byte-for-
/// byte the plain loop.
///
/// `twMerge` is the same merge for the 99.9% shape — a single already-joined
/// string (what `clsx()`-based `cn()` utils pass): no rest args, no toValue,
/// no join loop, straight into the `RC` memo and the `M` merge body. The two
/// share the same `RC` result memo and are byte-identical on single-string
/// inputs.
///
/// Whole-call results are memoized in `RC` (input -> output), the same trick
/// as tailwind-merge's opt-in result cache — but always on, because renders
/// (React etc.) repeat identical class strings constantly. Bounded at 8192
/// entries like the per-class parse memo `PC`; cleared wholesale when
/// exceeded, capping memory on long-lived apps with dynamic class strings.
/// The bound is configurable at runtime via the exported `setCacheSize(n)`
/// (tailwind-merge `cacheSize` parity); `0` disables both caches.
fn tw_merge_js(prefix: Option<&str>) -> String {
    let mut js = String::from(
        "let RC=Object.create(null),RCn=0,h;export function twMerge(s){h=RC[s];if(h!==undefined)return h;if(CS&&RCn>CS){RC=Object.create(null);RCn=0}return M(s)}export function twMergeJoin(...x){if(x.length===1&&typeof x[0]==='string'&&(h=RC[x[0]])!==undefined)return h;let l='';if(x.length===1&&typeof x[0]==='string')l=x[0];else for(const a of x)if(a){const v=typeof a==='string'?a:toValue(a);if(v){l&&(l+=' ');l+=v}}if((h=RC[l])!==undefined)return h;if(CS&&RCn>CS){RC=Object.create(null);RCn=0}return M(l)}function M(l){const t=l.trim();if(t.length<MC){let ws=-1;for(let i=0;i<t.length;i++){if(t.charCodeAt(i)<=32){ws=i;break}}const r=ws<0?t:t.replace(/\\s+/g,' ');if(CS){RC[l]=r;RCn++}return r}let seen=null,o='',st=t.length;while(st>0){let en=st;while(en>0&&t.charCodeAt(en-1)<=32)en--;let s=en;while(s>0&&t.charCodeAt(s-1)>32)s--;const c=t.slice(s,en);st=s;",
    );
    if let Some(p) = prefix {
        js.push_str(&format!(
            "if(!c.startsWith({})){{o=c+(o?' '+o:'');continue}}",
            js_string(&format!("{p}:"))
        ));
    }
    js.push_str(
        "const q=p(c);if(q[5]){o=c+(o?' '+o:'');continue}let f;if(A&&q[3]&&(q[2]+'/')in G)f=G[q[2]+'/'];else if(q[2]in G)f=G[q[2]];else if(C&&q[4]&&(q[4]+'arb')in G)f=G[q[4]+'arb'];else{o=c+(o?' '+o:'');continue}const v=q[1].length===0?'':q[1].length===1?q[1][0]:sm(q[1]).join(':'),k=v+(q[0]?'!':'')+f;if(seen&&seen.length>=64)seen=new Set(seen);if(seen&&(seen.add?seen.has(k):seen.includes(k)))continue;const cf=W[f],pre=v+(q[0]?'!':'');if(!seen)seen=[];if(seen.add)for(let j=0;j<cf.length;j++)seen.add(pre+cf[j]);else for(let j=0;j<cf.length;j++)seen.push(pre+cf[j]);o=c+(o?' '+o:'')}if(CS){RC[l]=o;RCn++}return o}",
    );
    js
}

/// Patterns-mode `twMergeJoin`/`twMerge`: same as `TW_MERGE_JS` (short-input
/// fast path, charCode token scan, lazy `seen`) with the pattern fallback
/// branch (D). `twMerge` is the single-string wrapper; `twMergeJoin` the
/// variadic one — see `tw_merge_js`.
/// Postfix-special clauses (font-size -> leading conflict, named containers)
/// are emitted only when those families exist.
fn tw_merge_patterns_js(p: &PatternTable, prefix: Option<&str>) -> String {
    let mut js = String::from(
        "let RC=Object.create(null),RCn=0,h;export function twMerge(s){h=RC[s];if(h!==undefined)return h;if(CS&&RCn>CS){RC=Object.create(null);RCn=0}return M(s)}export function twMergeJoin(...x){if(x.length===1&&typeof x[0]==='string'&&(h=RC[x[0]])!==undefined)return h;let l='';if(x.length===1&&typeof x[0]==='string')l=x[0];else for(const a of x)if(a){const v=typeof a==='string'?a:toValue(a);if(v){l&&(l+=' ');l+=v}}if((h=RC[l])!==undefined)return h;if(CS&&RCn>CS){RC=Object.create(null);RCn=0}return M(l)}function M(l){const t=l.trim();if(t.length<MC){let ws=-1;for(let i=0;i<t.length;i++){if(t.charCodeAt(i)<=32){ws=i;break}}const r=ws<0?t:t.replace(/\\s+/g,' ');if(CS){RC[l]=r;RCn++}return r}let seen=null,o='',st=t.length;while(st>0){let en=st;while(en>0&&t.charCodeAt(en-1)<=32)en--;let s=en;while(s>0&&t.charCodeAt(s-1)>32)s--;const c=t.slice(s,en);st=s;",
    );
    if let Some(pfx) = prefix {
        js.push_str(&format!(
            "if(!c.startsWith({})){{o=c+(o?' '+o:'');continue}}",
            js_string(&format!("{pfx}:"))
        ));
    }
    js.push_str(
        "const q=p(c);if(q[5]){o=c+(o?' '+o:'');continue}let f,cf;",
    );
    js.push_str(
        "if(A&&q[3]&&(q[2]+'/')in G)f=G[q[2]+'/'];else if(q[2]in G)f=G[q[2]];else if(C&&q[4]&&(q[4]+'arb')in G)f=G[q[4]+'arb'];else if(D){const r=m(q[2]);if(!r){o=c+(o?' '+o:'');continue}f=r[0];cf=r[1];if(A&&q[3]){",
    );
    if p.font_size.is_some() && p.leading.is_some() {
        js.push_str("if(FS!==undefined&&f===FS&&cf.indexOf(LD)<0)cf=cf.concat(LD);");
    }
    if p.container_type.is_some() && p.container_named.is_some() {
        js.push_str("if(CT!==undefined&&CN!==undefined&&f===CT&&cn(q[2]+q[6]))f=CN,cf=W[CN];");
    }
    js.push_str(
        "}}else{o=c+(o?' '+o:'');continue}if(cf===undefined)cf=W[f];if(cf===undefined)cf=[f];const v=q[1].length===0?'':q[1].length===1?q[1][0]:sm(q[1]).join(':'),k=v+(q[0]?'!':'')+f;if(seen&&seen.length>=64)seen=new Set(seen);if(seen&&(seen.add?seen.has(k):seen.includes(k)))continue;const pre=v+(q[0]?'!':'');if(!seen)seen=[];if(seen.add)for(let j=0;j<cf.length;j++)seen.add(pre+cf[j]);else for(let j=0;j<cf.length;j++)seen.push(pre+cf[j]);o=c+(o?' '+o:'')}if(CS){RC[l]=o;RCn++}return o}",
    );
    js
}

/// Overlay machinery emission: `NF` (compiled family count), the module
/// overlay constants `XO`/`XKW`/`XC`/`OW`, the `m2` matcher, the runtime
/// extend API (`--extend` only) and the `makeBundle` closure factory.
fn overlay_machinery_js(
    table: &ConflictTable,
    patterns: Option<&PatternTable>,
    pat_mode: bool,
    opts: &GenerateOptions,
) -> String {
    let mut js = String::new();

    // NF: first overlay family id; every compiled family id is below it.
    let n_compiled = if pat_mode {
        patterns.unwrap().family_names.len()
    } else {
        table.family_names.len()
    };
    js.push_str(&format!("const NF={n_compiled};\n"));

    // Build-time overlay (exact mode only; patterns mode compiles every
    // config family). A group holding ANY wildcard item becomes one overlay
    // family (ids NF, NF+1, ... by classGroups order) with a flat XO record
    // per item — its statics included; the compiled entries added by
    // apply_plugin_config stay, the G lookup hits first. Statics-only
    // groups stay compiled-only.
    let mut overlay_records: Vec<Record> = Vec::new();
    let mut xkw: Vec<String> = Vec::new();
    let mut theme_sets: Vec<Vec<String>> = Vec::new();
    let mut theme_ids: HashMap<String, usize> = HashMap::new();
    let mut group_to_index: HashMap<&str, usize> = HashMap::new();
    let mut xc: Vec<Vec<u16>> = Vec::new();
    let mut ow: BTreeMap<u16, Vec<u16>> = BTreeMap::new();
    if let Some(cfg) = opts.plugin {
        if !pat_mode {
            let mut fid = n_compiled as u16;
            for (group, items) in &cfg.class_groups {
                if !items.iter().any(|i| matches!(i, GroupItem::Wildcard(_))) {
                    continue;
                }
                group_to_index.insert(group.as_str(), xc.len());
                xc.push(vec![fid]);
                for item in items {
                    match item {
                        GroupItem::Static(cls) => overlay_records.push(Record {
                            name: cls.clone(),
                            elems: vec![
                                js_string(cls),
                                "0".to_string(),
                                fid.to_string(),
                                "0".to_string(),
                                "0".to_string(),
                            ],
                        }),
                        GroupItem::Wildcard(w) => {
                            let mut elems = vec![
                                js_string(&format!("{}-", w.prefix)),
                                "1".to_string(),
                                fid.to_string(),
                                "0".to_string(),
                                "1".to_string(),
                                w.specs.len().to_string(),
                            ];
                            for spec in &w.specs {
                                elems.push(
                                    overlay_spec_code(spec, &mut xkw, &mut theme_sets, &mut theme_ids, opts.ds)
                                        .to_string(),
                                );
                            }
                            overlay_records.push(Record {
                                name: format!("{}-", w.prefix),
                                elems,
                            });
                        }
                    }
                }
                fid += 1;
            }
            // Overlay edges: compiled -> overlay (OW), overlay -> compiled
            // and overlay -> overlay (XC). Compiled -> compiled edges were
            // already patched into the table by apply_plugin_config.
            for (group, targets) in &cfg.conflicting_class_groups {
                let src_compiled = table.family_exists(group).then(|| table.family_id_of(group));
                let src_overlay = group_to_index.get(group.as_str()).copied();
                for t in targets {
                    let t_compiled = table.family_exists(t).then(|| table.family_id_of(t));
                    let t_overlay = group_to_index.get(t.as_str()).copied();
                    if let Some(s) = src_compiled {
                        if let Some(to) = t_overlay {
                            let id = n_compiled as u16 + to as u16;
                            let e = ow.entry(s).or_default();
                            if !e.contains(&id) {
                                e.push(id);
                            }
                        }
                    }
                    if let Some(so) = src_overlay {
                        if let Some(tc) = t_compiled {
                            let e = &mut xc[so];
                            if !e.contains(&tc) {
                                e.push(tc);
                            }
                        }
                        if let Some(to) = t_overlay {
                            let id = n_compiled as u16 + to as u16;
                            let e = &mut xc[so];
                            if !e.contains(&id) {
                                e.push(id);
                            }
                        }
                    }
                }
            }
        }
    }

    // Theme sets (exact mode only — patterns mode emits TH/th with the
    // pattern tables). Only when a build-time overlay record needs one.
    if !theme_sets.is_empty() {
        js.push_str("const TH=[");
        for (i, set) in theme_sets.iter().enumerate() {
            if i > 0 {
                js.push(',');
            }
            js.push_str(&js_string(&set.join(",")));
        }
        js.push_str("];\n");
        js.push_str("const THS=[];function th(i){return THS[i]||(THS[i]=new Set(TH[i].split(',')))}\n");
    }
    // Exact mode has no pattern tables, so the value validators the overlay
    // matcher needs are emitted here.
    if !pat_mode {
        js.push_str(&validators_js());
    }

    // XO: overlay records in the same flat P format (name, wildcard, family
    // id, conflict wid (unused, 0), ngroups, (nitems, spec codes...)...).
    js.push_str("const XO=[");
    for (i, r) in overlay_records.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        for (j, e) in r.elems.iter().enumerate() {
            if j > 0 {
                js.push(',');
            }
            js.push_str(e);
        }
    }
    js.push_str("];\n");

    // XKW: overlay keyword strings (keyword codes index this array).
    js.push_str("const XKW=[");
    for (i, k) in xkw.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        js.push_str(&js_string(k));
    }
    js.push_str("];\n");

    // XC: per-overlay-family conflict id lists, own family id first.
    js.push_str("const XC=[");
    for (i, conflicts) in xc.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        js.push('[');
        for (j, id) in conflicts.iter().enumerate() {
            if j > 0 {
                js.push(',');
            }
            js.push_str(&id.to_string());
        }
        js.push(']');
    }
    js.push_str("];\n");

    // OW: sparse compiled family id -> overlay family ids (reverse edges:
    // a kept compiled class also drops the overlay families it edges).
    js.push_str("const OW={");
    for (i, (f, ids)) in ow.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        js.push_str(&js_key(&f.to_string()));
        js.push_str(":[");
        for (j, id) in ids.iter().enumerate() {
            if j > 0 {
                js.push(',');
            }
            js.push_str(&id.to_string());
        }
        js.push(']');
    }
    js.push_str("};\n");

    js.push_str(OVERLAY_MATCH_JS);

    if opts.extend {
        js.push_str(&extend_api_js());
    }
    js
}

/// Spec code of one exact-mode overlay record item. Mirrors the pattern
/// table's `spec_code`: keywords and theme sets are deduplicated per overlay,
/// and `--spacing` maps to the `spacing` type code.
fn overlay_spec_code(
    spec: &GroupSpec,
    xkw: &mut Vec<String>,
    theme_sets: &mut Vec<Vec<String>>,
    theme_ids: &mut HashMap<String, usize>,
    ds: Option<&DesignSystem>,
) -> u16 {
    match spec {
        GroupSpec::Type(t) => type_code(t) as u16,
        GroupSpec::Keyword(k) => {
            let idx = match xkw.iter().position(|x| x == k) {
                Some(i) => i,
                None => {
                    xkw.push(k.clone());
                    xkw.len() - 1
                }
            };
            (KW_OFFSET + idx) as u16
        }
        GroupSpec::ThemeKey { prefix, has_star } => {
            if prefix == "--spacing" && !*has_star {
                return type_code("spacing") as u16;
            }
            let ds = ds.expect("exact-mode plugin overlay theme specs need the design system");
            let idx = match theme_ids.get(prefix) {
                Some(i) => *i,
                None => {
                    let mut values: Vec<String> = ds
                        .theme
                        .vars
                        .keys()
                        .filter(|k| k.starts_with(prefix))
                        .map(|k| k[prefix.len()..].to_string())
                        .collect();
                    values.sort();
                    values.dedup();
                    let i = theme_sets.len();
                    theme_sets.push(values);
                    theme_ids.insert(prefix.clone(), i);
                    i
                }
            };
            (TH_OFFSET + idx) as u16
        }
    }
}

/// Named validator list for the `validators` export, in `TYPES` order
/// (the `.t` tag of entry i is i+1).
const VALIDATOR_NAMES: &[&str] = &[
    "isAny",
    "isNumber",
    "isInteger",
    "isPercentage",
    "isFraction",
    "isTshirtSize",
    "isLength",
    "isShadow",
    "isImage",
    "isUrl",
    "isPosition",
    "isRatio",
    "isWeight",
    "isFamilyName",
    "isAngle",
    "isTime",
    "isCustomIdent",
    "isSpacing",
    "isAnyNonArbitrary",
    "isArbitraryLength",
    "isArbitraryNumber",
    "isArbitraryInteger",
    "isArbitraryPercent",
    "isArbitraryFraction",
    "isArbitrarySize",
    "isArbitraryPosition",
    "isArbitraryShadow",
    "isArbitraryImage",
    "isArbitraryWeight",
    "isArbitraryFamilyName",
    "isArbitraryAngle",
    "isArbitraryTime",
    "isArbitraryRatio",
    "isArbitraryIdent",
    "isArbitraryUrl",
    "isArbitraryString",
    "isArbitraryCustomProperty",
    "isArbitraryFunction",
    "isArbitraryAny",
    "isVariableLength",
    "isVariableNumber",
    "isVariableInteger",
    "isVariablePercent",
    "isVariableFraction",
    "isVariableSize",
    "isVariablePosition",
    "isVariableShadow",
    "isVariableImage",
    "isVariableWeight",
    "isVariableFamilyName",
    "isVariableAngle",
    "isVariableTime",
    "isVariableIdent",
    "isVariableUrl",
    "isVariableString",
    "isVariableCustomProperty",
    "isVariableAny",
];

/// Runtime extend API (`--extend`): `TYPEMAP`, the tagged `validators`
/// object, `mergeConfigs`, the lazily-built compiled family-name map and
/// `extendTailwindMerge`/`createTailwindMerge`.
fn extend_api_js() -> String {
    let mut js = String::new();

    // TYPEMAP: every type name -> its spec code (1-based).
    js.push_str("const TYPEMAP={");
    for (i, t) in crate::patterns::TYPES.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        js.push_str(&js_key(t));
        js.push(':');
        js.push_str(&(i + 1).to_string());
    }
    js.push_str("};\n");

    // validators: named placeholders tagged with `.t` = type code; the
    // machinery reads `.t` for runtime config specs.
    js.push_str("const VN=[");
    for (i, n) in VALIDATOR_NAMES.iter().enumerate() {
        if i > 0 {
            js.push(',');
        }
        js.push_str(&js_string(n));
    }
    js.push_str(
        "];const validators={};for(let i=0;i<VN.length;i++){const f=(v)=>true;f.t=i+1;validators[VN[i]]=f}export{validators}\n",
    );

    // mergeConfigs: append-merge classGroups (top-level and `extend`-wrapped
    // identical), union conflictingClassGroups; fresh arrays, inputs untouched.
    js.push_str(
        "export function mergeConfigs(a,b){const g={},c={};for(const k in a.classGroups)(g[k]=g[k]||[]).push(...a.classGroups[k]);for(const k in a.conflictingClassGroups)(c[k]=c[k]||[]).push(...a.conflictingClassGroups[k]);for(const k in (a.extend||{}).classGroups)(g[k]=g[k]||[]).push(...(a.extend||{}).classGroups[k]);for(const k in (a.extend||{}).conflictingClassGroups)(c[k]=c[k]||[]).push(...(a.extend||{}).conflictingClassGroups[k]);for(const k in b.classGroups)(g[k]=g[k]||[]).push(...b.classGroups[k]);for(const k in b.conflictingClassGroups)(c[k]=c[k]||[]).push(...b.conflictingClassGroups[k]);for(const k in (b.extend||{}).classGroups)(g[k]=g[k]||[]).push(...(b.extend||{}).classGroups[k]);for(const k in (b.extend||{}).conflictingClassGroups)(c[k]=c[k]||[]).push(...(b.extend||{}).conflictingClassGroups[k]);return{classGroups:g,conflictingClassGroups:c}}\n",
    );

    // Lazily-built compiled family-name map (FN is static; built once on the
    // first extend call, copied per instance).
    js.push_str("let FM=0;function fmm(){if(!FM)FM=new Map(FN.map((n,i)=>[n,i]));return FM}\n");

    // extendTailwindMerge: builds an overlay descriptor for the given config
    // (or transformer over a minimal default) and returns a fresh bound
    // twMerge. The config is first normalized like `mergeConfigs`: top-level
    // and `extend`-wrapped classGroups/conflictingClassGroups both apply
    // (same append semantics), and unknown top-level keys throw
    // (`unsupported config key: <name>` — build-time parity). Class groups
    // always EXTEND the compiled catalog: strings and string arrays become
    // static records, `{prefix: [specs]}` objects wildcard records (specs:
    // `<type>` via TYPEMAP, tagged validator functions via `.t`, any other
    // string incl. "" a keyword; `--theme-*` strings are rejected — runtime
    // theme keys are unsupported). Edge names resolve against the compiled
    // families (< NF) and this instance's own groups (>= NF); unknown names
    // are dead edges.
    js.push_str(
        "export function extendTailwindMerge(c){if(typeof c==='function')c=c({classGroups:{},conflictingClassGroups:{}});for(const k in c)if(k!=='classGroups'&&k!=='conflictingClassGroups'&&k!=='extend')throw new Error('unsupported config key: '+k);c=mergeConfigs(c,{});const xo=XO.slice(),xkw=XKW.slice(),xc=XC.slice(),ow=Object.assign({},OW);const nm=new Map(fmm());const b=xc.length;let j=0;for(const g in c.classGroups){const fid=NF+b+j;if(!nm.has(g))nm.set(g,fid);for(const it of c.classGroups[g]){if(typeof it==='string')xo.push(it,0,fid,0,0);else if(Array.isArray(it)){for(let q=0;q<it.length;q++)xo.push(it[q],0,fid,0,0)}else for(const p in it){xo.push(p?p+'-':'',1,fid,0,1,it[p].length);for(let q=0;q<it[p].length;q++){const s=it[p][q];let code;if(typeof s==='function')code=s.t;else if(typeof s==='string'){if(s[0]==='<'){code=TYPEMAP[s.slice(1,-1)];if(!code)throw new Error('unknown type: '+s)}else if(s.startsWith('--'))throw new Error('runtime theme keys are not supported: '+s);else{xkw.push(s);code=4000+xkw.length-1}}else throw new Error('invalid group spec');xo.push(code)}}}xc.push([fid]);j++}for(const g in c.conflictingClassGroups){const sid=nm.get(g);if(sid===undefined)continue;for(const t of c.conflictingClassGroups[g]){const tid=nm.get(t);if(tid===undefined)continue;if(sid<NF){if(tid>=NF){const a=ow[sid]||(ow[sid]=[]);if(a.indexOf(tid)<0)a.push(tid)}}else{const ci=sid-NF;if(xc[ci].indexOf(tid)<0)xc[ci].push(tid)}}}return makeBundle({xo,xkw,xc,ow})}export const createTailwindMerge=extendTailwindMerge;\n",
    );
    js
}

/// Overlay-mode merge tail: `makeBundle(ov)` binds the overlay descriptor
/// (`{xo,xkw,xc,ow}`) plus a per-instance whole-call result cache and
/// returns the bound `twMerge` function (the extend bundle's `twMerge` is
/// variadic, matching the extend API; `twMergeJoin` aliases it). The merge
/// loop mirrors the compiled variants: G lookup first, then (patterns mode)
/// `m()`, then `m2`; kept compiled classes accumulate `W` plus their `OW`
/// overlay edges, kept overlay classes accumulate `XC`. Results that
/// involved an overlay match are not cached (overlay ids are
/// instance-specific).
fn tw_merge_extend_js(pat_mode: bool, p: Option<&PatternTable>, prefix: Option<&str>) -> String {
    let mut js = String::from(
        "function makeBundle(ov){let RC=Object.create(null),RCn=0,h;function twMerge(...x){if(x.length===1&&typeof x[0]==='string'&&(h=RC[x[0]])!==undefined)return h;let l='';if(x.length===1&&typeof x[0]==='string')l=x[0];else for(const a of x)if(a){const v=typeof a==='string'?a:toValue(a);if(v){l&&(l+=' ');l+=v}}if((h=RC[l])!==undefined)return h;if(CS&&RCn>CS){RC=Object.create(null);RCn=0}return M(l)}const twMergeJoin=twMerge;function M(l){const t=l.trim();if(t.length<MC){let ws=-1;for(let i=0;i<t.length;i++){if(t.charCodeAt(i)<=32){ws=i;break}}const r=ws<0?t:t.replace(/\\s+/g,' ');if(CS){RC[l]=r;RCn++}return r}let seen=null,o='',oc=0,st=t.length;while(st>0){let en=st;while(en>0&&t.charCodeAt(en-1)<=32)en--;let s=en;while(s>0&&t.charCodeAt(s-1)>32)s--;const c=t.slice(s,en);st=s;",
    );
    if let Some(pfx) = prefix {
        js.push_str(&format!(
            "if(!c.startsWith({})){{o=c+(o?' '+o:'');continue}}",
            js_string(&format!("{pfx}:"))
        ));
    }
    js.push_str(
        "const q=p(c);if(q[5]){o=c+(o?' '+o:'');continue}let f,cf;if(A&&q[3]&&(q[2]+'/')in G)f=G[q[2]+'/'];else if(q[2]in G)f=G[q[2]];else if(C&&q[4]&&(q[4]+'arb')in G)f=G[q[4]+'arb'];",
    );
    if pat_mode {
        js.push_str(
            "else if(D){const r=m(q[2]);if(!r){const r2=m2(q[2],ov);if(r2<0){o=c+(o?' '+o:'');continue}oc=1;f=NF+r2;cf=ov.xc[r2]}else{f=r[0];cf=r[1];if(A&&q[3]){",
        );
        let pat = p.unwrap();
        if pat.font_size.is_some() && pat.leading.is_some() {
            js.push_str("if(FS!==undefined&&f===FS&&cf.indexOf(LD)<0)cf=cf.concat(LD);");
        }
        if pat.container_type.is_some() && pat.container_named.is_some() {
            js.push_str("if(CT!==undefined&&CN!==undefined&&f===CT&&cn(q[2]+q[6]))f=CN,cf=W[CN];");
        }
        // Closes: if(A&&q[3]), the m2-miss else, and the else if(D) branch.
        js.push_str("}}}");
    } else {
        js.push_str(
            "else{const r=m2(q[2],ov);if(r<0){o=c+(o?' '+o:'');continue}oc=1;f=NF+r;cf=ov.xc[r]}",
        );
    }
    js.push_str(
        "if(cf===undefined)cf=W[f];if(cf===undefined)cf=[f];const v=q[1].length===0?'':q[1].length===1?q[1][0]:sm(q[1]).join(':'),k=v+(q[0]?'!':'')+f;if(seen&&seen.length>=64)seen=new Set(seen);if(seen&&(seen.add?seen.has(k):seen.includes(k)))continue;const pre=v+(q[0]?'!':'');if(!seen)seen=[];if(seen.add){for(let j=0;j<cf.length;j++)seen.add(pre+cf[j]);const wf=ov.ow[f];if(wf)for(let j=0;j<wf.length;j++)seen.add(pre+wf[j])}else{for(let j=0;j<cf.length;j++)seen.push(pre+cf[j]);const wf=ov.ow[f];if(wf)for(let j=0;j<wf.length;j++)seen.push(pre+wf[j])}o=c+(o?' '+o:'')}if(CS&&!oc){RC[l]=o;RCn++}return o}return twMerge}",
    );
    js.push_str(
        "const MO={xo:XO,xkw:XKW,xc:XC,ow:OW};const TM=makeBundle(MO);export const twMerge=TM;export const twMergeJoin=TM;\n",
    );
    js
}

/// Overlay matcher `m2(v,o)`: linear scan over the instance's flat overlay
/// records (same layout as `P`), mirroring `m()`'s spec-check semantics —
/// keyword match (incl. the explicit empty keyword, the only way an empty
/// suffix matches), type codes and theme sets. Returns the overlay family
/// index or -1. Arbitrary properties are not special-cased: in patterns
/// mode the compiled `m()` handles them first, exact mode has no property
/// table.
const OVERLAY_MATCH_JS: &str = r#"function m2(v,o){if(v[0]==='-')v=v.slice(1);const xo=o.xo,xkw=o.xkw;for(let i=0;i<xo.length;){const n=xo[i++],w=xo[i++],f=xo[i++],wid=xo[i++],g=xo[i++];if(!(w?(v.length>n.length&&v.startsWith(n))||(v===n.slice(0,-1)):v===n)){for(let j=0;j<g;j++){const c2=xo[i++];i+=c2}continue}const val=w?(v.length>n.length?v.slice(n.length):''):'';let ok=1;for(let j=0;j<g;j++){const c2=xo[i++];let a=0;for(let k=0;k<c2;k++){const s=xo[i++];a=a||(val===''?s>=4000&&xkw[s-4000]==='':s>=5000?th(s-5000).has(val):s>=4000?xkw[s-4000]===val:s&&VT(s,val))}if(!a){ok=0;break}}if(ok)return f-NF}return -1}"#;

/// (type name, JS case body) for `VT`. The `a-*`/`v-*` bodies use `l`
/// (arbitrary label, '' when absent) and `x` (arbitrary inner value).
const VT_CASES: &[(&str, &str)] = &[
    ("any", "1"),
    ("url", "1"),
    ("weight", "N(v)"),
    ("family-name", "!AV(v)&&!V(v)"),
    ("any-non-arbitrary", "!AV(v)&&!V(v)"),
    ("number", "N(v)"),
    ("integer", "I(v)"),
    ("percentage", "v.endsWith('%')&&N(v.slice(0,-1))"),
    ("fraction", "F(v)"),
    ("tshirt", r"/^(\d+(\.\d+)?)?(xs|sm|md|lg|xl)$/.test(v)"),
    ("length", "L(v)"),
    ("shadow", r"/^(inset_)?-?((\d+)?\.?(\d+)[a-z]+|0)_-?((\d+)?\.?(\d+)[a-z]+|0)/.test(v)"),
    (
        "image",
        r"/^(url|image|image-set|cross-fade|element|(repeating-)?(linear|radial|conic)-gradient)\(.+\)$/.test(v)",
    ),
    (
        "position",
        "v==='center'||v==='top'||v==='bottom'||v==='left'||v==='right'||v==='top-left'||v==='left-top'||v==='top-right'||v==='right-top'||v==='bottom-right'||v==='right-bottom'||v==='bottom-left'||v==='left-bottom'",
    ),
    ("ratio", "F(v)||N(v)"),
    ("angle", "N(v)||v.endsWith('deg')||v.endsWith('grad')||v.endsWith('rad')||v.endsWith('turn')"),
    ("time", "N(v)||v.endsWith('ms')||v.endsWith('s')"),
    ("custom-ident", r"/^[a-zA-Z_\-\\][\w\-\\]*$/.test(v)"),
    ("spacing", "v==='px'||N(v)||AV(v)||V(v)"),
    ("a-length", "l?l==='length':L(x)"),
    ("a-number", "l?l==='number':N(x)"),
    ("a-integer", "l?(l==='number'||l==='integer'):N(x)"),
    ("a-percent", "l?(l==='position'||l==='percentage'):(x.endsWith('%')&&N(x.slice(0,-1)))"),
    ("a-fraction", "l?(l==='number'||l==='ratio'):F(x)"),
    ("a-size", "l!==''&&(l==='length'||l==='size'||l==='bg-size')"),
    ("a-position", "l!==''&&(l==='position'||l==='percentage')"),
    ("a-shadow", r"l?l==='shadow':/^(inset_)?-?((\d+)?\.?(\d+)[a-z]+|0)_-?((\d+)?\.?(\d+)[a-z]+|0)/.test(x)"),
    (
        "a-image",
        r"l?(l==='image'||l==='url'):/^(url|image|image-set|cross-fade|element|(repeating-)?(linear|radial|conic)-gradient)\(.+\)$/.test(x)",
    ),
    ("a-weight", "l?(l==='number'||l==='weight'):1"),
    ("a-family-name", "l==='family-name'"),
    ("a-angle", "l===''||l==='angle'"),
    ("a-time", "l===''||l==='time'"),
    ("a-ratio", "l===''||l==='ratio'"),
    ("a-ident", "l===''||l==='custom-ident'"),
    ("a-url", "l===''||l==='url'"),
    ("a-string", "AV(v)"),
    ("a-custom-property", "AV(v)"),
    ("a-function", "AV(v)"),
    ("a-any", "AV(v)"),
    ("v-length", "l==='length'"),
    ("v-family-name", "l==='family-name'"),
    ("v-position", "l==='position'||l==='percentage'"),
    ("v-size", "l==='length'||l==='size'||l==='bg-size'"),
    ("v-image", "l==='image'||l==='url'"),
    ("v-shadow", "l?l==='shadow':1"),
    ("v-weight", "l?(l==='number'||l==='weight'):1"),
    ("v-angle", "l===''||l==='angle'"),
    ("v-time", "l===''||l==='time'"),
    ("v-ident", "l===''||l==='custom-ident'"),
    ("v-url", "l===''||l==='url'"),
    ("v-percent", "l==='percentage'"),
    ("v-number", "l==='number'||l==='integer'"),
    ("v-fraction", "l==='number'||l==='ratio'"),
    ("v-string", "V(v)"),
    ("v-custom-property", "V(v)"),
    ("v-any", "V(v)"),
];

/// Value validators: exact behavioral port of `values.rs` plus the
/// `SpecItem::matches` type switch (`VT`, case numbers from `type_code`).
fn validators_js() -> String {
    let mut js = String::from(
        r#"const LU=/\d+(%|px|r?em|[sdl]?v([hwib]|min|max)|pt|pc|in|cm|mm|cap|ch|ex|r?lh|cq(w|h|i|b|min|max))|\b(calc|min|max|clamp)\(.+\)|^0$/;const CF=/^(rgba?|hsla?|hwb|(ok)?(lab|lch)|color-mix)\(.+\)$/;function N(v){return /^[+-]?(\d+(\.\d*)?|\.\d+)([eE][+-]?\d+)?$/.test(v)||v==='inf'||v==='+inf'||v==='-inf'||v==='infinity'||v==='+infinity'||v==='-infinity'||v==='NaN'||v==='nan'}function I(v){return /^[+-]?\d+$/.test(v)}function L(v){return LU.test(v)&&!CF.test(v)}function AV(v){return /^\[(?:(\w[\w-]*):)?(.+)\]$/.test(v)}function V(v){return /^\((?:(\w[\w-]*):)?(.+)\)$/.test(v)}function F(v){return /^\d+(\.\d+)?\/\d+(\.\d+)?$/.test(v)}function P1(v){const m=/^\[(?:(\w[\w-]*):)?(.+)\]$/.exec(v);return m?[m[1]||'',m[2]]:0}function P2(v){const m=/^\((?:(\w[\w-]*):)?(.+)\)$/.exec(v);return m?[m[1]||'',m[2]]:0}"#,
    );
    js.push_str("function VT(c,v){switch(c){");
    for (name, body) in VT_CASES {
        let code = type_code(name);
        if name.starts_with("a-") || name.starts_with("v-") {
            let parser = if name.starts_with("v-") { "P2" } else { "P1" };
            js.push_str(&format!(
                "case {code}:{{const p={parser}(v);if(!p)return 0;const l=p[0],x=p[1];return {body}}};"
            ));
        } else {
            js.push_str(&format!("case {code}:return {body};"));
        }
    }
    js.push_str("}return 0}");
    js
}

/// Patterns-mode matcher: lazy theme-set/keyword helpers plus `m(v)`, which
/// resolves an unseen class against the pattern table and returns
/// `[family, conflicts]` or 0. Arbitrary properties resolve via the PR
/// property->family table so they merge with the standard classes they write.
/// The flat `P` scan is indexed by the leading-segment table `BI` (see the
/// generator): only the spans whose prefix equals the first two chars of `v`
/// (the first char for one-char `v`) are scanned.
const PATTERN_MATCH_JS: &str = r#"
const THS=[];function th(i){return THS[i]||(THS[i]=new Set(TH[i].split(',')))}let K;function kws(){if(K===undefined)K=KW.split(',');return K}function cn(v){return v.startsWith('@container')&&((v[10]==='/'&&v[11])||(v[11]==='s'&&v[16]&&v.slice(10).startsWith('-size/'))||(v[11]==='n'&&v[18]&&v.slice(10).startsWith('-normal/')))}function m(v){if(v[0]==='['&&v[v.length-1]===']'){const x=v.slice(1,-1),c=x.indexOf(':');if(c>0){const p=x.slice(0,c);if(p&&PR[p]!==undefined){const f=PR[p];return[f,W[f]]}const k='arbitrary..'+p;return[k,[k]]}}if(v[0]==='-')v=v.slice(1);const rs=BI[v.length>1?v[0]+v[1]:v[0]];if(!rs)return 0;for(let r=0;r<rs.length;r++){for(let i=rs[r][0];i<rs[r][1];){const n=P[i++],w=P[i++],f=P[i++],wid=P[i++],g=P[i++];if(!(w?v.length>n.length&&v.startsWith(n):v===n)){for(let j=0;j<g;j++){const c2=P[i++];i+=c2}continue}const val=w?v.slice(n.length):'';let ok=1;for(let j=0;j<g;j++){const c2=P[i++];let a=0;for(let k=0;k<c2;k++){const s=P[i++];a=a||(s>=5000?th(s-5000).has(val):s>=4000?kws()[s-4000]===val:s&&VT(s,val))}if(!a){ok=0;break}}if(ok)return [f,W2[wid]]}}return 0}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::conflict::apply_plugin_config;
    use crate::patterns::PatternTable;
    use crate::theme::Theme;
    use crate::utility::DesignSystem;

    fn table(classes: &[&str]) -> ConflictTable {
        let css = r#"
            @theme { --spacing: 0.25rem; }
            @utility p-* { padding: --value(--spacing, <length>); }
            @utility block { display: block; }
        "#;
        let prog = crate::css::parse(css);
        let ds = DesignSystem::from_css(Theme::from_program(&prog), prog.utilities, &[]);
        let classes: Vec<String> = classes.iter().map(|s| s.to_string()).collect();
        ConflictTable::from_classes(&ds, &classes, None)
    }

    #[test]
    fn generates_esm() {
        let t = table(&["p-2", "block"]);
        let js = generate_js(
            &t,
            None,
            &GenerateOptions {
                prefix: None,
                patterns: false,
                ..Default::default()
            },
        );
        assert!(js.contains("export function twMerge(s)"));
        assert!(js.contains("export function twMergeJoin"));
        assert!(js.contains("export function twJoin"));
        assert!(js.contains("p-2"));
    }

    #[test]
    fn generates_prefix() {
        let t = table(&["tw:block", "tw:inline"]);
        let js = generate_js(
            &t,
            None,
            &GenerateOptions {
                prefix: Some("tw"),
                patterns: false,
                ..Default::default()
            },
        );
        assert!(js.contains("const PREFIX=\"tw\""));
        // Prefix tokenizer skip: non-prefixed tokens are emitted without
        // parsing; the unprefixed bundle must not carry the skip.
        assert!(
            js.contains("if(!c.startsWith(\"tw:\")){o=c+(o?' '+o:'');continue}"),
            "prefixed bundle must skip non-prefixed tokens before parsing"
        );
        let plain = generate_js(
            &t,
            None,
            &GenerateOptions {
                prefix: None,
                patterns: false,
                ..Default::default()
            },
        );
        assert!(
            !plain.contains("if(!c.startsWith(\"tw:\"))"),
            "unprefixed bundle must not contain the prefix skip"
        );
    }

    #[test]
    fn mc_exact_table_derived_patterns_floor() {
        let ds = crate::default_design_system();
        let classes: Vec<String> = vec!["overflow-x-auto".into(), "overflow-x-hidden".into()];
        let t = ConflictTable::from_classes(&ds, &classes, None);
        // conflict pair: 15+1+16 = 32; duplicate pair of the shorter class:
        // 2*15+1 = 31 — the duplicate bound wins, so MC = 31.
        assert_eq!(t.min_conflict_pair_len(), Some(31));
        let exact = generate_js(
            &t,
            None,
            &GenerateOptions {
                prefix: None,
                patterns: false,
                ..Default::default()
            },
        );
        assert!(exact.contains("const MC=31;"));
        let pat = PatternTable::from_design_system(&ds);
        let tp = ConflictTable::from_classes_seeded(&ds, &classes, None, pat.family_names.clone());
        let patterns = generate_js(
            &tp,
            Some(&pat),
            &GenerateOptions {
                prefix: None,
                patterns: true,
                ..Default::default()
            },
        );
        assert!(
            patterns.contains("const MC=7;"),
            "patterns mode must keep the default-grammar floor, not the table-derived min"
        );
    }

    #[test]
    fn mc_sentinel_when_no_conflicting_pair() {
        // Empty table: nothing can ever merge, sentinel fires.
        let t = table(&[]);
        assert_eq!(t.min_conflict_pair_len(), None);
        let js = generate_js(
            &t,
            None,
            &GenerateOptions {
                prefix: None,
                patterns: false,
                ..Default::default()
            },
        );
        assert!(js.contains("const MC=Number.MAX_SAFE_INTEGER;"));
        // No conflicts, but duplicates still dedupe: "p-2 p-2" (7 chars)
        // must reach the full merge, so the duplicate bound (2*3+1 = 7) is
        // the minimum even without any conflicting pair.
        let t = table(&["p-2", "block"]);
        assert_eq!(t.min_conflict_pair_len(), Some(7));
        let t = table(&["p-1", "p-2"]);
        assert_eq!(t.min_conflict_pair_len(), Some(7));
    }

    #[test]
    fn patterns_mode_emits_pattern_tables() {
        let css = r#"
            @theme { --spacing: 0.25rem; --text-2xl: 1.5rem; }
            @utility p-* { padding: --value(--spacing, <length>); }
            @utility text-* { font-size: --value(--text-*, <tshirt>); }
            @utility block { display: block; }
        "#;
        let prog = crate::css::parse(css);
        let ds = DesignSystem::from_css(Theme::from_program(&prog), prog.utilities, &[]);
        let pat = PatternTable::from_design_system(&ds);
        let classes: Vec<String> = vec!["p-2".to_string(), "block".to_string()];
        let t = ConflictTable::from_classes_seeded(&ds, &classes, None, pat.family_names.clone());
        let js = generate_js(
            &t,
            Some(&pat),
            &GenerateOptions {
                prefix: None,
                patterns: true,
                ..Default::default()
            },
        );
        assert!(
            js.contains("const P=["),
            "patterns bundle must contain the pattern table"
        );
        assert!(
            js.contains("const FN=["),
            "patterns bundle must contain family names"
        );
        assert!(
            js.contains("const TH=["),
            "patterns bundle must contain theme sets"
        );
        assert!(js.contains("export function twMerge(s)"));
        assert!(js.contains("export function twMergeJoin"));

        let exact = generate_js(
            &t,
            None,
            &GenerateOptions {
                prefix: None,
                patterns: false,
                ..Default::default()
            },
        );
        assert!(
            !exact.contains("const P=["),
            "exact bundle must not contain the pattern table"
        );
    }

    #[test]
    fn parse_js_variants_stay_in_sync() {
        let pat = PARSE_PATTERNS_JS
            .replace("[0,[],c,0,0,1,0]", "[0,[],c,0,0,1]")
            .replace("r=[im,m,b,po,ar,0,po?c.slice(pp):0]", "r=[im,m,b,po,ar,0]");
        assert_eq!(pat, PARSE_JS);
    }

    #[test]
    fn b_spans_cover_every_record_exactly_once() {
        // Synthetic records with non-contiguous same-prefix runs and a
        // one-char name (which must key on its single char).
        let records = vec![
            Record {
                name: "ab".into(),
                elems: vec![String::new(); 3],
            },
            Record {
                name: "ab".into(),
                elems: vec![String::new(); 2],
            },
            Record {
                name: "ac".into(),
                elems: vec![String::new(); 4],
            },
            Record {
                name: "ab".into(),
                elems: vec![String::new(); 5],
            },
            Record {
                name: "a".into(),
                elems: vec![String::new(); 2],
            },
            Record {
                name: "ab".into(),
                elems: vec![String::new(); 1],
            },
        ];
        let spans = leading_segment_spans(&records);
        assert_eq!(spans["ab"], vec![(0, 5), (9, 14), (16, 17)]);
        assert_eq!(spans["ac"], vec![(5, 9)]);
        assert_eq!(spans["a"], vec![(14, 16)]);
        // No overlap: every flat index is inside at most one span.
        let mut ranges: Vec<(usize, usize)> = spans.values().flatten().copied().collect();
        ranges.sort_unstable();
        for w in ranges.windows(2) {
            assert!(
                w[0].1 <= w[1].0,
                "spans overlap or cross: {:?}",
                (w[0], w[1])
            );
        }
        // Every record covered by exactly one span of its own prefix, at its
        // exact flat position (index 0 = first record's first element).
        let mut covered: BTreeMap<(usize, usize), usize> = BTreeMap::new();
        let mut flat = 0;
        for r in &records {
            let key: String = r.name.chars().take(2).collect();
            let end = flat + r.elems.len();
            let ss = spans.get(&key).expect("bucket key present");
            let hits = ss
                .iter()
                .filter(|(a, b)| *a <= flat && end <= *b)
                .count();
            assert_eq!(
                hits, 1,
                "record {:?} at flat {}..{} must be inside exactly one span of its own prefix",
                r.name, flat, end
            );
            *covered.entry((flat, end)).or_insert(0) += 1;
            flat = end;
        }
        assert!(
            covered.values().all(|&c| c == 1),
            "each record range must be covered exactly once"
        );
    }

    #[test]
    fn b_emission_has_no_duplicate_keys() {
        let ds = crate::default_design_system();
        let patterns = PatternTable::from_design_system(&ds);
        let classes: Vec<String> = vec!["p-2".into(), "block".into()];
        let t = ConflictTable::from_classes_seeded(&ds, &classes, None, patterns.family_names.clone());
        let js = generate_js(
            &t,
            Some(&patterns),
            &GenerateOptions {
                prefix: None,
                patterns: true,
                ..Default::default()
            },
        );
        // B: exactly one emitted key per prefix (duplicate object-literal
        // keys would collapse with only the LAST span surviving).
        let b_start = js.find("const BI=").expect("BI emitted");
        let b_end = js[b_start..].find("});\n").expect("BI terminates") + b_start;
        let body = &js[b_start + "const BI=Object.assign(Object.create(null),{".len()..b_end];
        let keys: Vec<&str> = body
            .split(',')
            .filter(|s| s.ends_with(":["))
            .map(|s| s.split(':').next().unwrap())
            .collect();
        let mut sorted = keys.clone();
        sorted.sort();
        sorted.dedup();
        assert_eq!(
            sorted.len(),
            keys.len(),
            "duplicate B keys in emission: {:?}",
            keys
        );
    }

    #[test]
    fn exact_plugin_emits_overlay() {
        let css = r#"
            @theme { --spacing: 0.25rem; }
            @utility p-* { padding: --value(--spacing, <length>); }
            @utility block { display: block; }
        "#;
        let prog = crate::css::parse(css);
        let cfg = crate::config::parse_config_json(
            r#"{
                "classGroups": {
                    "rtl.ps": [{ "ps": ["<length>"] }],
                    "rtl.auto": [{ "psx": ["auto", "--spacing"] }],
                    "rtl.static": ["rtl-start"]
                },
                "conflictingClassGroups": { "p": ["rtl.ps"], "rtl.ps": ["p"] }
            }"#,
        )
        .unwrap();
        let ds = DesignSystem::from_css(
            Theme::from_program(&prog),
            prog.utilities,
            &cfg.to_synthetic_utilities(),
        );
        let classes: Vec<String> = vec!["p-2".to_string(), "block".to_string()];
        let mut t = ConflictTable::from_classes(&ds, &classes, None);
        let unresolved = apply_plugin_config(&mut t, &ds, &cfg, None);
        let js = generate_js(
            &t,
            None,
            &GenerateOptions {
                prefix: None,
                patterns: false,
                plugin: Some(&cfg),
                extend: false,
                ds: Some(&ds),
            },
        );
        assert!(
            js.contains("const NF="),
            "overlay bundles must emit the compiled family count"
        );
        assert!(js.contains("const XO=["));
        // Overlay records mirror the flat P format. Config keys sort
        // alphabetically (serde_json without preserve_order): rtl.auto gets
        // overlay index 0, rtl.ps index 1.
        let nf = t.family_names.len();
        assert!(
            js.contains(&format!("\"psx-\",1,{nf},0,1,2,4000,18")),
            "wildcard overlay record must mirror the P format: {:?}",
            js.find("const XO=[").map(|i| &js[i..i + 200])
        );
        assert!(js.contains(&format!("\"ps-\",1,{},0,1,1,7", nf + 1)));
        // --spacing maps to the spacing type code (18), keywords go to XKW.
        assert!(js.contains("\"auto\""), "keyword must land in XKW");
        // Edge (p -> rtl.ps): p compiled -> OW; rtl.ps overlay -> XC.
        assert!(
            js.contains(&format!("const OW={{\"0\":[{}]}};", nf + 1)),
            "OW must map compiled p to the overlay rtl.ps family"
        );
        assert!(
            js.contains(&format!("const XC=[[{nf}],[{},0]];", nf + 1)),
            "XC must start with own-id lists"
        );
        assert!(js.contains("function m2("));
        assert!(js.contains("function makeBundle("));
        assert!(js.contains("const MC=7;"), "plugin mode floors MC at 7");
        assert!(
            !js.contains("extendTailwindMerge"),
            "no extend API without --extend"
        );
        // Unresolved edges are returned for the caller; the overlay emission
        // itself iterates the config edges (covers mixed compiled+overlay).
        assert_eq!(
            unresolved,
            vec![
                ("p".to_string(), vec!["rtl.ps".to_string()]),
                ("rtl.ps".to_string(), vec!["p".to_string()]),
            ]
        );
    }

    #[test]
    fn extend_emits_runtime_api() {
        let ds = crate::default_design_system();
        let patterns = PatternTable::from_design_system(&ds);
        let classes: Vec<String> = vec!["p-2".into(), "block".into()];
        let t = ConflictTable::from_classes_seeded(&ds, &classes, None, patterns.family_names.clone());
        let js = generate_js(
            &t,
            Some(&patterns),
            &GenerateOptions {
                prefix: None,
                patterns: true,
                extend: true,
                ..Default::default()
            },
        );
        assert!(js.contains("export function extendTailwindMerge("));
        assert!(js.contains("export function mergeConfigs("));
        assert!(js.contains("export const createTailwindMerge="));
        assert!(js.contains("const TYPEMAP={"));
        assert!(js.contains("export{validators}"));
        assert!(js.contains("const validators={}"));
        assert!(js.contains("const XO=[]"));
        assert!(js.contains("const XKW=[]"));
        assert!(js.contains("const XC=[]"));
        assert!(js.contains("const OW={}"));
        assert!(js.contains("function makeBundle("));
        assert!(js.contains("function m2("));
        assert!(js.contains("const MC=7;"), "extend mode floors MC at 7");
        assert!(js.contains("export const twMerge=TM"), "module twMerge = makeBundle(MO)");
        // The emitted runtime machinery must be brace/paren balanced (the
        // overlay lines carry no brace/paren characters inside data strings).
        for line in js.lines() {
            if ["const TYPEMAP", "const VN", "mergeConfigs", "fmm()", "extendTailwindMerge", "makeBundle", "m2(v,o)"]
                .iter()
                .any(|needle| line.contains(needle))
            {
                let opens = line.matches('{').count() + line.matches('(').count();
                let closes = line.matches('}').count() + line.matches(')').count();
                assert_eq!(
                    opens, closes,
                    "unbalanced machinery line: {}",
                    &line[..line.len().min(160)]
                );
            }
        }
    }

    /// Extract the emitted `W` table rows ([family id] -> conflict ids).
    fn w_rows(js: &str) -> Vec<Vec<u16>> {
        let start = js.find("const W=[").expect("W emitted") + "const W=[".len();
        let end = js[start..].find("];").expect("W terminates") + start;
        js[start..end]
            .split("],[")
            .map(|part| {
                part.trim_start_matches('[')
                    .trim_end_matches(']')
                    .split(',')
                    .filter_map(|s| s.parse().ok())
                    .collect()
            })
            .collect()
    }

    #[test]
    fn patterns_plugin_patches_family_conflict_rows() {
        // Patterns mode compiles every plugin family into the pattern table,
        // so the --config edges patch the per-family W rows directly instead
        // of emitting overlay machinery.
        let css = r#"
            @theme { --spacing: 0.25rem; }
            @utility p-* { padding: --value(--spacing, <length>); }
            @utility block { display: block; }
        "#;
        let prog = crate::css::parse(css);
        let cfg = crate::config::parse_config_json(
            r#"{
                "classGroups": {
                    "rtl.ps": [{ "ps": ["<length>"] }],
                    "rtl.pe": [{ "pe": ["<length>"] }]
                },
                "conflictingClassGroups": { "p": ["rtl.ps", "rtl.pe"] }
            }"#,
        )
        .unwrap();
        let ds = DesignSystem::from_css(
            Theme::from_program(&prog),
            prog.utilities,
            &cfg.to_synthetic_utilities(),
        );
        let pat = PatternTable::from_design_system(&ds);
        let classes: Vec<String> = vec!["p-2".to_string(), "block".to_string()];
        let t = ConflictTable::from_classes_seeded(&ds, &classes, None, pat.family_names.clone());
        let js = generate_js(
            &t,
            Some(&pat),
            &GenerateOptions {
                prefix: None,
                patterns: true,
                plugin: Some(&cfg),
                ..Default::default()
            },
        );
        let rows = w_rows(&js);
        let p = pat.family_names.iter().position(|n| n == "p").unwrap();
        let ps = pat.family_names.iter().position(|n| n == "rtl.ps").unwrap();
        let pe = pat.family_names.iter().position(|n| n == "rtl.pe").unwrap();
        assert!(
            rows[p].contains(&(ps as u16)) && rows[p].contains(&(pe as u16)),
            "W row for p must include the edge targets rtl.ps/rtl.pe: {:?}",
            rows[p]
        );
        assert!(
            !rows[ps].contains(&(p as u16)),
            "W row for rtl.ps must NOT include p — the edge is one-directional: {:?}",
            rows[ps]
        );
        // Patterns mode compiles every config family into the pattern table,
        // so the overlay machinery is emitted empty (the same `overlay` flag
        // drives both modes, but only exact mode fills XO/XC/OW).
        assert!(
            js.contains("const XO=[];"),
            "patterns+plugin must emit only empty overlay records"
        );
        assert!(
            js.contains("const XC=[];") && js.contains("const OW={};"),
            "patterns+plugin must emit empty overlay conflict tables"
        );
    }

    #[test]
    fn exact_extend_emits_family_names() {
        let css = r#"
            @theme { --spacing: 0.25rem; }
            @utility p-* { padding: --value(--spacing, <length>); }
            @utility block { display: block; }
        "#;
        let prog = crate::css::parse(css);
        let ds = DesignSystem::from_css(Theme::from_program(&prog), prog.utilities, &[]);
        let classes: Vec<String> = vec!["p-2".to_string(), "block".to_string()];
        let t = ConflictTable::from_classes(&ds, &classes, None);
        let js = generate_js(
            &t,
            None,
            &GenerateOptions {
                prefix: None,
                patterns: false,
                extend: true,
                ..Default::default()
            },
        );
        assert!(js.contains("const FN=["), "exact-extend needs FN");
        assert!(js.contains("const XO=[]"));
        assert!(js.contains("export function extendTailwindMerge("));
    }
}
