//! JS module generation: a dependency-free ESM `twMerge`/`twJoin` bundle
//! containing only the classes a project uses, with feature-flagged runtime
//! helpers. No Tailwind parser at runtime — O(1) table lookups.

use crate::conflict::ConflictTable;

pub struct GenerateOptions<'a> {
    pub prefix: Option<&'a str>,
}

pub fn generate_js(table: &ConflictTable, opts: &GenerateOptions) -> String {
    let mut js = String::new();
    js.push_str("// Generated by twm-gen — do not edit. Dependency-free ESM (Node 18+).\n");

    let needs_postfix = table.needs_postfix;
    let needs_important = table.needs_important;
    let needs_fallback = !table.arb_fallbacks.is_empty();

    js.push_str(&format!(
        "const A={needs_postfix},B={needs_important},C={needs_fallback};\n"
    ));
    if let Some(p) = opts.prefix {
        js.push_str(&format!("const PREFIX={};\n", js_string(p)));
    }

    // GROUPS: base class name -> family id. Postfix variants get a trailing
    // '/' key; arbitrary-value fallbacks get a 'prefix-arb' key.
    // Object.create(null) gives a prototype-less table so the hot path can use
    // the fast `key in G` operator (no inherited-key false positives, and `in`
    // is far cheaper than Object.prototype.hasOwnProperty.call).
    js.push_str("const G=Object.assign(Object.create(null),{");
    let mut first = true;
    let emit = |js: &mut String, first: &mut bool, key: &str, id: u16| {
        if !*first {
            js.push(',');
        }
        *first = false;
        js.push_str(&js_key(key));
        js.push(':');
        js.push_str(&id.to_string());
    };
    let mut entries: Vec<(&String, &crate::conflict::ClassKey)> = table.entries.iter().collect();
    entries.sort_by(|a, b| a.0.cmp(b.0));
    for (base, key) in entries {
        emit(&mut js, &mut first, base, family_id_of(table, &key.family));
    }
    let mut postfix: Vec<(&String, &crate::conflict::ClassKey)> =
        table.postfix_entries.iter().collect();
    postfix.sort_by(|a, b| a.0.cmp(b.0));
    for (base, key) in postfix {
        emit(&mut js, &mut first, base, family_id_of(table, &key.family));
    }
    let mut fallbacks: Vec<(&String, &crate::conflict::ClassKey)> =
        table.arb_fallbacks.iter().collect();
    fallbacks.sort_by(|a, b| a.0.cmp(b.0));
    for (prefix, key) in fallbacks {
        emit(&mut js, &mut first, &format!("{prefix}arb"), family_id_of(table, &key.family));
    }
    js.push_str("});\n");

    // W: family id -> list of family ids it conflicts with (own family
    // first, then generated properties and directed edges).
    let family_conflicts = table.family_conflicts();
    js.push_str("const W=[");
    for (f, conflict_ids) in family_conflicts.iter().enumerate() {
        if f > 0 {
            js.push(',');
        }
        js.push('[');
        for (i, id) in conflict_ids.iter().enumerate() {
            if i > 0 {
                js.push(',');
            }
            js.push_str(&id.to_string());
        }
        js.push(']');
    }
    js.push_str("];\n");

    js.push_str(PARSE_JS);
    js.push_str(SORT_MODIFIERS_JS);
    js.push_str(TW_JOIN_JS);

    js.push_str(TW_MERGE_JS);
    js
}

/// Family id of a family name in the table.
fn family_id_of(table: &ConflictTable, name: &str) -> u16 {
    table
        .family_names
        .iter()
        .position(|n| n == name)
        .map(|i| i as u16)
        .unwrap_or(0)
}

/// JSON-quoted JS string literal.
fn js_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '"' => out.push_str("\\\""),
            '\\' => out.push_str("\\\\"),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

/// Object key: unquoted when it is a valid JS identifier, quoted otherwise.
fn js_key(s: &str) -> String {
    let mut chars = s.chars();
    let valid = match chars.next() {
        Some(c) if c.is_ascii_alphabetic() || c == '_' || c == '$' => {
            chars.all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '$')
        }
        _ => false,
    };
    if valid {
        s.to_string()
    } else {
        js_string(s)
    }
}

/// Candidate parser: modifiers, important flag, postfix position and
/// arbitrary fallback prefix. Mirrors `parse-class-name.ts` (plus prefix
/// stripping and the feature flags A=postfix, B=important, C=fallback).
/// Results are memoized per class string (same optimization tailwind-merge's
/// `cachedParseClassName` applies; class names repeat heavily in practice).
const PARSE_JS: &str = r#"
const PC=new Map();function p(c){let r=PC.get(c);if(r!==undefined)return r;if(typeof PREFIX!=='undefined'){const f=PREFIX+':';if(!c.startsWith(f)){r=[0,[],c,0,0,1];PC.set(c,r);return r}c=c.slice(f.length)}const m=[];let bs=0,ps=0,ms=0,pp=-1;for(let i=0;i<c.length;i++){const ch=c[i];if(bs===0&&ps===0){if(ch===':'){m.push(c.slice(ms,i));ms=i+1;continue}if(ch==='/'&&pp<0)pp=i}if(ch==='[')bs++;else if(ch===']')bs--;else if(ch==='(')ps++;else if(ch===')')ps--}let b=ms===0?c:c.slice(ms);let im=0;if(B){if(b.endsWith('!')){b=b.slice(0,-1);im=1}else if(b.startsWith('!')){b=b.slice(1);im=1}}let po=0;if(A&&pp>ms){po=1;b=b.slice(0,pp-ms)}let ar=0;if(C){const ai=b.search(/[\[(]/);if(ai>0)ar=b.slice(0,ai)}r=[im,m,b,po,ar,0];PC.set(c,r);return r}
"#;

/// Modifier sorting with order-sensitive anchors (port of `sort-modifiers.ts`).
const SORT_MODIFIERS_JS: &str = r#"
const OS=new Set(['*','**','after','backdrop','before','details-content','file','first-letter','first-line','marker','placeholder','selection']);function sm(x){const r=[];let s=[];for(let i=0;i<x.length;i++){const m=x[i];if(m[0]==='['||OS.has(m)){if(s.length){s.sort();r.push(...s);s=[]}r.push(m)}else s.push(m)}if(s.length){s.sort();r.push(...s)}return r}
"#;

/// `twJoin` (port of `tw-join.ts`, itself derived from clsx).
const TW_JOIN_JS: &str = r#"
export function twJoin(...x){let s='';for(let i=0;i<x.length;i++){const a=x[i];if(a){const v=toValue(a);if(v){s&&(s+=' ');s+=v}}}return s}
function toValue(m){if(typeof m==='string')return m;let s='';for(let k=0;k<m.length;k++){if(m[k]){const v=toValue(m[k]);if(v){s&&(s+=' ');s+=v}}}return s}
"#;

/// `twMerge` (port of `merge-classlist.ts`): right-to-left, last class wins,
/// conflict key = sorted modifiers + important + family. `seen` is an array of
/// family keys checked with `includes` (linear scan beats a Set for the tiny
/// per-family conflict lists) — the same trick tailwind-merge's benchmarked
/// `mergeClassList` uses.
const TW_MERGE_JS: &str = r#"
export function twMerge(...x){const l=twJoin(...x),seen=[],n=l.trim().split(/\s+/);let o='';for(let i=n.length-1;i>=0;i--){const c=n[i],q=p(c);if(q[5]){o=c+(o?' '+o:'');continue}let f;if(A&&q[3]&&(q[2]+'/')in G)f=G[q[2]+'/'];else if(q[2]in G)f=G[q[2]];else if(C&&q[4]&&(q[4]+'arb')in G)f=G[q[4]+'arb'];else{o=c+(o?' '+o:'');continue}const v=q[1].length===0?'':q[1].length===1?q[1][0]:sm(q[1]).join(':'),k=v+(q[0]?'!':'')+f;if(seen.includes(k))continue;const cf=W[f],pre=v+(q[0]?'!':'');for(let j=0;j<cf.length;j++)seen.push(pre+cf[j]);o=c+(o?' '+o:'')}return o}
"#;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::theme::Theme;
    use crate::utility::DesignSystem;

    fn table(classes: &[&str]) -> ConflictTable {
        let css = r#"
            @theme { --spacing: 0.25rem; }
            @utility p-* { padding: --value(--spacing, <length>); }
            @utility block { display: block; }
        "#;
        let prog = crate::css::parse(css);
        let ds = DesignSystem::from_css(Theme::from_program(&prog), prog.utilities);
        let classes: Vec<String> = classes.iter().map(|s| s.to_string()).collect();
        ConflictTable::from_classes(&ds, &classes, None)
    }

    #[test]
    fn generates_esm() {
        let t = table(&["p-2", "block"]);
        let js = generate_js(&t, &GenerateOptions { prefix: None });
        assert!(js.contains("export function twMerge"));
        assert!(js.contains("export function twJoin"));
        assert!(js.contains("p-2"));
    }

    #[test]
    fn generates_prefix() {
        let t = table(&["tw:block", "tw:inline"]);
        let js = generate_js(&t, &GenerateOptions { prefix: Some("tw") });
        assert!(js.contains("const PREFIX=\"tw\""));
    }
}
